// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.1
// source: api/proto/e2mgr/e2mgr.proto

package e2mgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages for node operations
type GetNodesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeType         *string                `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3,oneof" json:"node_type,omitempty"`
	ConnectionStatus *string                `protobuf:"bytes,2,opt,name=connection_status,json=connectionStatus,proto3,oneof" json:"connection_status,omitempty"`
	Limit            *uint32                `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset           *uint32                `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodesRequest) GetNodeType() string {
	if x != nil && x.NodeType != nil {
		return *x.NodeType
	}
	return ""
}

func (x *GetNodesRequest) GetConnectionStatus() string {
	if x != nil && x.ConnectionStatus != nil {
		return *x.ConnectionStatus
	}
	return ""
}

func (x *GetNodesRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetNodesRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*E2Node              `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodesResponse) GetNodes() []*E2Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetNodesResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *E2Node                `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeResponse) GetNode() *E2Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UpdateNodeConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Configuration *NodeConfiguration     `protobuf:"bytes,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeConfigurationRequest) Reset() {
	*x = UpdateNodeConfigurationRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeConfigurationRequest) ProtoMessage() {}

func (x *UpdateNodeConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeConfigurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNodeConfigurationRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateNodeConfigurationRequest) GetConfiguration() *NodeConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type UpdateNodeConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeConfigurationResponse) Reset() {
	*x = UpdateNodeConfigurationResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeConfigurationResponse) ProtoMessage() {}

func (x *UpdateNodeConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeConfigurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNodeConfigurationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateNodeConfigurationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetNodeHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHealthRequest) Reset() {
	*x = GetNodeHealthRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHealthRequest) ProtoMessage() {}

func (x *GetNodeHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHealthRequest.ProtoReflect.Descriptor instead.
func (*GetNodeHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodeHealthRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *NodeHealth            `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHealthResponse) Reset() {
	*x = GetNodeHealthResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHealthResponse) ProtoMessage() {}

func (x *GetNodeHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHealthResponse.ProtoReflect.Descriptor instead.
func (*GetNodeHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{9}
}

func (x *GetNodeHealthResponse) GetHealth() *NodeHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{10}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *E2ManagerStats        `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatsResponse) GetStats() *E2ManagerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// E2 Setup procedure messages
type E2SetupRequest struct {
	state                        protoimpl.MessageState   `protogen:"open.v1"`
	TransactionId                uint32                   `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	GlobalE2NodeId               *GlobalE2NodeID          `protobuf:"bytes,2,opt,name=global_e2_node_id,json=globalE2NodeId,proto3" json:"global_e2_node_id,omitempty"`
	RanFunctions                 []*RANFunction           `protobuf:"bytes,3,rep,name=ran_functions,json=ranFunctions,proto3" json:"ran_functions,omitempty"`
	E2NodeComponentConfigAddList []*E2NodeComponentConfig `protobuf:"bytes,4,rep,name=e2_node_component_config_add_list,json=e2NodeComponentConfigAddList,proto3" json:"e2_node_component_config_add_list,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *E2SetupRequest) Reset() {
	*x = E2SetupRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SetupRequest) ProtoMessage() {}

func (x *E2SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SetupRequest.ProtoReflect.Descriptor instead.
func (*E2SetupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{12}
}

func (x *E2SetupRequest) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *E2SetupRequest) GetGlobalE2NodeId() *GlobalE2NodeID {
	if x != nil {
		return x.GlobalE2NodeId
	}
	return nil
}

func (x *E2SetupRequest) GetRanFunctions() []*RANFunction {
	if x != nil {
		return x.RanFunctions
	}
	return nil
}

func (x *E2SetupRequest) GetE2NodeComponentConfigAddList() []*E2NodeComponentConfig {
	if x != nil {
		return x.E2NodeComponentConfigAddList
	}
	return nil
}

type E2SetupResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TransactionId        uint32                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success              bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Cause                string                 `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	RanFunctionsAccepted []*RANFunctionAccepted `protobuf:"bytes,4,rep,name=ran_functions_accepted,json=ranFunctionsAccepted,proto3" json:"ran_functions_accepted,omitempty"`
	RanFunctionsRejected []*RANFunctionRejected `protobuf:"bytes,5,rep,name=ran_functions_rejected,json=ranFunctionsRejected,proto3" json:"ran_functions_rejected,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *E2SetupResponse) Reset() {
	*x = E2SetupResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SetupResponse) ProtoMessage() {}

func (x *E2SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SetupResponse.ProtoReflect.Descriptor instead.
func (*E2SetupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{13}
}

func (x *E2SetupResponse) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *E2SetupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *E2SetupResponse) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *E2SetupResponse) GetRanFunctionsAccepted() []*RANFunctionAccepted {
	if x != nil {
		return x.RanFunctionsAccepted
	}
	return nil
}

func (x *E2SetupResponse) GetRanFunctionsRejected() []*RANFunctionRejected {
	if x != nil {
		return x.RanFunctionsRejected
	}
	return nil
}

type ConfigurationUpdateRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	TransactionId    uint32                   `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	NodeId           string                   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConfigUpdateList []*E2NodeComponentConfig `protobuf:"bytes,3,rep,name=config_update_list,json=configUpdateList,proto3" json:"config_update_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigurationUpdateRequest) Reset() {
	*x = ConfigurationUpdateRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdateRequest) ProtoMessage() {}

func (x *ConfigurationUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdateRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigurationUpdateRequest) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ConfigurationUpdateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConfigurationUpdateRequest) GetConfigUpdateList() []*E2NodeComponentConfig {
	if x != nil {
		return x.ConfigUpdateList
	}
	return nil
}

type ConfigurationUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint32                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Cause         string                 `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationUpdateResponse) Reset() {
	*x = ConfigurationUpdateResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdateResponse) ProtoMessage() {}

func (x *ConfigurationUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdateResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigurationUpdateResponse) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ConfigurationUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigurationUpdateResponse) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint32                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Cause         string                 `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{16}
}

func (x *ResetRequest) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ResetRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResetRequest) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint32                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{17}
}

func (x *ResetResponse) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Data models
type E2Node struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GlobalE2NodeId   *GlobalE2NodeID        `protobuf:"bytes,2,opt,name=global_e2_node_id,json=globalE2NodeId,proto3" json:"global_e2_node_id,omitempty"`
	ConnectionStatus string                 `protobuf:"bytes,3,opt,name=connection_status,json=connectionStatus,proto3" json:"connection_status,omitempty"`
	IpAddress        string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Port             uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	ServiceModels    []*ServiceModel        `protobuf:"bytes,6,rep,name=service_models,json=serviceModels,proto3" json:"service_models,omitempty"`
	RanFunctions     []*RANFunction         `protobuf:"bytes,7,rep,name=ran_functions,json=ranFunctions,proto3" json:"ran_functions,omitempty"`
	LastUpdate       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Subscriptions    []*SubscriptionInfo    `protobuf:"bytes,9,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	SetupRequest     *E2SetupRequestData    `protobuf:"bytes,10,opt,name=setup_request,json=setupRequest,proto3" json:"setup_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *E2Node) Reset() {
	*x = E2Node{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2Node) ProtoMessage() {}

func (x *E2Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2Node.ProtoReflect.Descriptor instead.
func (*E2Node) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{18}
}

func (x *E2Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *E2Node) GetGlobalE2NodeId() *GlobalE2NodeID {
	if x != nil {
		return x.GlobalE2NodeId
	}
	return nil
}

func (x *E2Node) GetConnectionStatus() string {
	if x != nil {
		return x.ConnectionStatus
	}
	return ""
}

func (x *E2Node) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *E2Node) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *E2Node) GetServiceModels() []*ServiceModel {
	if x != nil {
		return x.ServiceModels
	}
	return nil
}

func (x *E2Node) GetRanFunctions() []*RANFunction {
	if x != nil {
		return x.RanFunctions
	}
	return nil
}

func (x *E2Node) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *E2Node) GetSubscriptions() []*SubscriptionInfo {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *E2Node) GetSetupRequest() *E2SetupRequestData {
	if x != nil {
		return x.SetupRequest
	}
	return nil
}

type GlobalE2NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlmnId        string                 `protobuf:"bytes,1,opt,name=plmn_id,json=plmnId,proto3" json:"plmn_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalE2NodeID) Reset() {
	*x = GlobalE2NodeID{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalE2NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalE2NodeID) ProtoMessage() {}

func (x *GlobalE2NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalE2NodeID.ProtoReflect.Descriptor instead.
func (*GlobalE2NodeID) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{19}
}

func (x *GlobalE2NodeID) GetPlmnId() string {
	if x != nil {
		return x.PlmnId
	}
	return ""
}

func (x *GlobalE2NodeID) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GlobalE2NodeID) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ServiceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Functions     []*RANFunction         `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceModel) Reset() {
	*x = ServiceModel{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceModel) ProtoMessage() {}

func (x *ServiceModel) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceModel.ProtoReflect.Descriptor instead.
func (*ServiceModel) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{20}
}

func (x *ServiceModel) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *ServiceModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceModel) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceModel) GetFunctions() []*RANFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

type RANFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Oid           string                 `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Definition    []byte                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Revision      uint32                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RANFunction) Reset() {
	*x = RANFunction{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RANFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RANFunction) ProtoMessage() {}

func (x *RANFunction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RANFunction.ProtoReflect.Descriptor instead.
func (*RANFunction) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{21}
}

func (x *RANFunction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RANFunction) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *RANFunction) GetDefinition() []byte {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *RANFunction) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RANFunction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RANFunctionAccepted struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RanFunctionId       uint32                 `protobuf:"varint,1,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	RanFunctionRevision uint32                 `protobuf:"varint,2,opt,name=ran_function_revision,json=ranFunctionRevision,proto3" json:"ran_function_revision,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RANFunctionAccepted) Reset() {
	*x = RANFunctionAccepted{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RANFunctionAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RANFunctionAccepted) ProtoMessage() {}

func (x *RANFunctionAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RANFunctionAccepted.ProtoReflect.Descriptor instead.
func (*RANFunctionAccepted) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{22}
}

func (x *RANFunctionAccepted) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *RANFunctionAccepted) GetRanFunctionRevision() uint32 {
	if x != nil {
		return x.RanFunctionRevision
	}
	return 0
}

type RANFunctionRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RanFunctionId uint32                 `protobuf:"varint,1,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	Cause         string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RANFunctionRejected) Reset() {
	*x = RANFunctionRejected{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RANFunctionRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RANFunctionRejected) ProtoMessage() {}

func (x *RANFunctionRejected) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RANFunctionRejected.ProtoReflect.Descriptor instead.
func (*RANFunctionRejected) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{23}
}

func (x *RANFunctionRejected) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *RANFunctionRejected) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type E2NodeComponentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceType string                 `protobuf:"bytes,1,opt,name=interface_type,json=interfaceType,proto3" json:"interface_type,omitempty"`
	InterfaceId   uint32                 `protobuf:"varint,2,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	Configuration []byte                 `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2NodeComponentConfig) Reset() {
	*x = E2NodeComponentConfig{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2NodeComponentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentConfig) ProtoMessage() {}

func (x *E2NodeComponentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentConfig.ProtoReflect.Descriptor instead.
func (*E2NodeComponentConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{24}
}

func (x *E2NodeComponentConfig) GetInterfaceType() string {
	if x != nil {
		return x.InterfaceType
	}
	return ""
}

func (x *E2NodeComponentConfig) GetInterfaceId() uint32 {
	if x != nil {
		return x.InterfaceId
	}
	return 0
}

func (x *E2NodeComponentConfig) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type SubscriptionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	XappId         string                 `protobuf:"bytes,2,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
	RanFunctionId  uint32                 `protobuf:"varint,3,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionInfo) Reset() {
	*x = SubscriptionInfo{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionInfo) ProtoMessage() {}

func (x *SubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionInfo.ProtoReflect.Descriptor instead.
func (*SubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{25}
}

func (x *SubscriptionInfo) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionInfo) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

func (x *SubscriptionInfo) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *SubscriptionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type E2SetupRequestData struct {
	state                        protoimpl.MessageState   `protogen:"open.v1"`
	TransactionId                uint32                   `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	GlobalE2NodeId               *GlobalE2NodeID          `protobuf:"bytes,2,opt,name=global_e2_node_id,json=globalE2NodeId,proto3" json:"global_e2_node_id,omitempty"`
	RanFunctions                 []*RANFunction           `protobuf:"bytes,3,rep,name=ran_functions,json=ranFunctions,proto3" json:"ran_functions,omitempty"`
	E2NodeComponentConfigAddList []*E2NodeComponentConfig `protobuf:"bytes,4,rep,name=e2_node_component_config_add_list,json=e2NodeComponentConfigAddList,proto3" json:"e2_node_component_config_add_list,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *E2SetupRequestData) Reset() {
	*x = E2SetupRequestData{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2SetupRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SetupRequestData) ProtoMessage() {}

func (x *E2SetupRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SetupRequestData.ProtoReflect.Descriptor instead.
func (*E2SetupRequestData) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{26}
}

func (x *E2SetupRequestData) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *E2SetupRequestData) GetGlobalE2NodeId() *GlobalE2NodeID {
	if x != nil {
		return x.GlobalE2NodeId
	}
	return nil
}

func (x *E2SetupRequestData) GetRanFunctions() []*RANFunction {
	if x != nil {
		return x.RanFunctions
	}
	return nil
}

func (x *E2SetupRequestData) GetE2NodeComponentConfigAddList() []*E2NodeComponentConfig {
	if x != nil {
		return x.E2NodeComponentConfigAddList
	}
	return nil
}

type NodeConfiguration struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Parameters       map[string]string        `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ComponentConfigs []*E2NodeComponentConfig `protobuf:"bytes,2,rep,name=component_configs,json=componentConfigs,proto3" json:"component_configs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeConfiguration) Reset() {
	*x = NodeConfiguration{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfiguration) ProtoMessage() {}

func (x *NodeConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfiguration.ProtoReflect.Descriptor instead.
func (*NodeConfiguration) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{27}
}

func (x *NodeConfiguration) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *NodeConfiguration) GetComponentConfigs() []*E2NodeComponentConfig {
	if x != nil {
		return x.ComponentConfigs
	}
	return nil
}

type NodeHealth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsHealthy       bool                   `protobuf:"varint,2,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	LastHealthCheck *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_health_check,json=lastHealthCheck,proto3" json:"last_health_check,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeHealth) Reset() {
	*x = NodeHealth{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealth) ProtoMessage() {}

func (x *NodeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealth.ProtoReflect.Descriptor instead.
func (*NodeHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{28}
}

func (x *NodeHealth) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHealth) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *NodeHealth) GetLastHealthCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHealthCheck
	}
	return nil
}

func (x *NodeHealth) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type E2ManagerStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodesByType         map[string]uint32      `protobuf:"bytes,1,rep,name=nodes_by_type,json=nodesByType,proto3" json:"nodes_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	NodesByStatus       map[string]uint32      `protobuf:"bytes,2,rep,name=nodes_by_status,json=nodesByStatus,proto3" json:"nodes_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalNodes          uint32                 `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ActiveSubscriptions uint32                 `protobuf:"varint,4,opt,name=active_subscriptions,json=activeSubscriptions,proto3" json:"active_subscriptions,omitempty"`
	LastUpdated         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *E2ManagerStats) Reset() {
	*x = E2ManagerStats{}
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2ManagerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2ManagerStats) ProtoMessage() {}

func (x *E2ManagerStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_e2mgr_e2mgr_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2ManagerStats.ProtoReflect.Descriptor instead.
func (*E2ManagerStats) Descriptor() ([]byte, []int) {
	return file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP(), []int{29}
}

func (x *E2ManagerStats) GetNodesByType() map[string]uint32 {
	if x != nil {
		return x.NodesByType
	}
	return nil
}

func (x *E2ManagerStats) GetNodesByStatus() map[string]uint32 {
	if x != nil {
		return x.NodesByStatus
	}
	return nil
}

func (x *E2ManagerStats) GetTotalNodes() uint32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *E2ManagerStats) GetActiveSubscriptions() uint32 {
	if x != nil {
		return x.ActiveSubscriptions
	}
	return 0
}

func (x *E2ManagerStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_api_proto_e2mgr_e2mgr_proto protoreflect.FileDescriptor

const file_api_proto_e2mgr_e2mgr_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/e2mgr/e2mgr.proto\x12\x05e2mgr\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\x0fGetNodesRequest\x12 \n" +
	"\tnode_type\x18\x01 \x01(\tH\x00R\bnodeType\x88\x01\x01\x120\n" +
	"\x11connection_status\x18\x02 \x01(\tH\x01R\x10connectionStatus\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\rH\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\rH\x03R\x06offset\x88\x01\x01B\f\n" +
	"\n" +
	"_node_typeB\x14\n" +
	"\x12_connection_statusB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"M\n" +
	"\x10GetNodesResponse\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.e2mgr.E2NodeR\x05nodes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"4\n" +
	"\x0fGetNodeResponse\x12!\n" +
	"\x04node\x18\x01 \x01(\v2\r.e2mgr.E2NodeR\x04node\"y\n" +
	"\x1eUpdateNodeConfigurationRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12>\n" +
	"\rconfiguration\x18\x02 \x01(\v2\x18.e2mgr.NodeConfigurationR\rconfiguration\"U\n" +
	"\x1fUpdateNodeConfigurationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11DeleteNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"H\n" +
	"\x12DeleteNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x14GetNodeHealthRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"B\n" +
	"\x15GetNodeHealthResponse\x12)\n" +
	"\x06health\x18\x01 \x01(\v2\x11.e2mgr.NodeHealthR\x06health\"\x11\n" +
	"\x0fGetStatsRequest\"?\n" +
	"\x10GetStatsResponse\x12+\n" +
	"\x05stats\x18\x01 \x01(\v2\x15.e2mgr.E2ManagerStatsR\x05stats\"\x99\x02\n" +
	"\x0eE2SetupRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12@\n" +
	"\x11global_e2_node_id\x18\x02 \x01(\v2\x15.e2mgr.GlobalE2NodeIDR\x0eglobalE2NodeId\x127\n" +
	"\rran_functions\x18\x03 \x03(\v2\x12.e2mgr.RANFunctionR\franFunctions\x12e\n" +
	"!e2_node_component_config_add_list\x18\x04 \x03(\v2\x1c.e2mgr.E2NodeComponentConfigR\x1ce2NodeComponentConfigAddList\"\x8c\x02\n" +
	"\x0fE2SetupResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12P\n" +
	"\x16ran_functions_accepted\x18\x04 \x03(\v2\x1a.e2mgr.RANFunctionAcceptedR\x14ranFunctionsAccepted\x12P\n" +
	"\x16ran_functions_rejected\x18\x05 \x03(\v2\x1a.e2mgr.RANFunctionRejectedR\x14ranFunctionsRejected\"\xa8\x01\n" +
	"\x1aConfigurationUpdateRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12J\n" +
	"\x12config_update_list\x18\x03 \x03(\v2\x1c.e2mgr.E2NodeComponentConfigR\x10configUpdateList\"t\n" +
	"\x1bConfigurationUpdateResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\"d\n" +
	"\fResetRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\"P\n" +
	"\rResetResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xeb\x03\n" +
	"\x06E2Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x11global_e2_node_id\x18\x02 \x01(\v2\x15.e2mgr.GlobalE2NodeIDR\x0eglobalE2NodeId\x12+\n" +
	"\x11connection_status\x18\x03 \x01(\tR\x10connectionStatus\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12:\n" +
	"\x0eservice_models\x18\x06 \x03(\v2\x13.e2mgr.ServiceModelR\rserviceModels\x127\n" +
	"\rran_functions\x18\a \x03(\v2\x12.e2mgr.RANFunctionR\franFunctions\x12;\n" +
	"\vlast_update\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12=\n" +
	"\rsubscriptions\x18\t \x03(\v2\x17.e2mgr.SubscriptionInfoR\rsubscriptions\x12>\n" +
	"\rsetup_request\x18\n" +
	" \x01(\v2\x19.e2mgr.E2SetupRequestDataR\fsetupRequest\"V\n" +
	"\x0eGlobalE2NodeID\x12\x17\n" +
	"\aplmn_id\x18\x01 \x01(\tR\x06plmnId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\x80\x01\n" +
	"\fServiceModel\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x120\n" +
	"\tfunctions\x18\x04 \x03(\v2\x12.e2mgr.RANFunctionR\tfunctions\"\x8d\x01\n" +
	"\vRANFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\tR\x03oid\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\fR\n" +
	"definition\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\rR\brevision\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"q\n" +
	"\x13RANFunctionAccepted\x12&\n" +
	"\x0fran_function_id\x18\x01 \x01(\rR\rranFunctionId\x122\n" +
	"\x15ran_function_revision\x18\x02 \x01(\rR\x13ranFunctionRevision\"S\n" +
	"\x13RANFunctionRejected\x12&\n" +
	"\x0fran_function_id\x18\x01 \x01(\rR\rranFunctionId\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\tR\x05cause\"\x87\x01\n" +
	"\x15E2NodeComponentConfig\x12%\n" +
	"\x0einterface_type\x18\x01 \x01(\tR\rinterfaceType\x12!\n" +
	"\finterface_id\x18\x02 \x01(\rR\vinterfaceId\x12$\n" +
	"\rconfiguration\x18\x03 \x01(\fR\rconfiguration\"\x94\x01\n" +
	"\x10SubscriptionInfo\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\axapp_id\x18\x02 \x01(\tR\x06xappId\x12&\n" +
	"\x0fran_function_id\x18\x03 \x01(\rR\rranFunctionId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x9d\x02\n" +
	"\x12E2SetupRequestData\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12@\n" +
	"\x11global_e2_node_id\x18\x02 \x01(\v2\x15.e2mgr.GlobalE2NodeIDR\x0eglobalE2NodeId\x127\n" +
	"\rran_functions\x18\x03 \x03(\v2\x12.e2mgr.RANFunctionR\franFunctions\x12e\n" +
	"!e2_node_component_config_add_list\x18\x04 \x03(\v2\x1c.e2mgr.E2NodeComponentConfigR\x1ce2NodeComponentConfigAddList\"\xe7\x01\n" +
	"\x11NodeConfiguration\x12H\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2(.e2mgr.NodeConfiguration.ParametersEntryR\n" +
	"parameters\x12I\n" +
	"\x11component_configs\x18\x02 \x03(\v2\x1c.e2mgr.E2NodeComponentConfigR\x10componentConfigs\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\n" +
	"NodeHealth\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x02 \x01(\bR\tisHealthy\x12F\n" +
	"\x11last_health_check\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHealthCheck\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\"\xc3\x03\n" +
	"\x0eE2ManagerStats\x12J\n" +
	"\rnodes_by_type\x18\x01 \x03(\v2&.e2mgr.E2ManagerStats.NodesByTypeEntryR\vnodesByType\x12P\n" +
	"\x0fnodes_by_status\x18\x02 \x03(\v2(.e2mgr.E2ManagerStats.NodesByStatusEntryR\rnodesByStatus\x12\x1f\n" +
	"\vtotal_nodes\x18\x03 \x01(\rR\n" +
	"totalNodes\x121\n" +
	"\x14active_subscriptions\x18\x04 \x01(\rR\x13activeSubscriptions\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1a>\n" +
	"\x10NodesByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a@\n" +
	"\x12NodesByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x012\x96\x05\n" +
	"\tE2Manager\x12;\n" +
	"\bGetNodes\x12\x16.e2mgr.GetNodesRequest\x1a\x17.e2mgr.GetNodesResponse\x128\n" +
	"\aGetNode\x12\x15.e2mgr.GetNodeRequest\x1a\x16.e2mgr.GetNodeResponse\x12h\n" +
	"\x17UpdateNodeConfiguration\x12%.e2mgr.UpdateNodeConfigurationRequest\x1a&.e2mgr.UpdateNodeConfigurationResponse\x12A\n" +
	"\n" +
	"DeleteNode\x12\x18.e2mgr.DeleteNodeRequest\x1a\x19.e2mgr.DeleteNodeResponse\x12J\n" +
	"\rGetNodeHealth\x12\x1b.e2mgr.GetNodeHealthRequest\x1a\x1c.e2mgr.GetNodeHealthResponse\x12;\n" +
	"\bGetStats\x12\x16.e2mgr.GetStatsRequest\x1a\x17.e2mgr.GetStatsResponse\x12>\n" +
	"\rHandleE2Setup\x12\x15.e2mgr.E2SetupRequest\x1a\x16.e2mgr.E2SetupResponse\x12b\n" +
	"\x19HandleConfigurationUpdate\x12!.e2mgr.ConfigurationUpdateRequest\x1a\".e2mgr.ConfigurationUpdateResponse\x128\n" +
	"\vHandleReset\x12\x13.e2mgr.ResetRequest\x1a\x14.e2mgr.ResetResponseB1Z/github.com/oran/near-rt-ric-new/api/proto/e2mgrb\x06proto3"

var (
	file_api_proto_e2mgr_e2mgr_proto_rawDescOnce sync.Once
	file_api_proto_e2mgr_e2mgr_proto_rawDescData []byte
)

func file_api_proto_e2mgr_e2mgr_proto_rawDescGZIP() []byte {
	file_api_proto_e2mgr_e2mgr_proto_rawDescOnce.Do(func() {
		file_api_proto_e2mgr_e2mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_e2mgr_e2mgr_proto_rawDesc), len(file_api_proto_e2mgr_e2mgr_proto_rawDesc)))
	})
	return file_api_proto_e2mgr_e2mgr_proto_rawDescData
}

var file_api_proto_e2mgr_e2mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_proto_e2mgr_e2mgr_proto_goTypes = []any{
	(*GetNodesRequest)(nil),                 // 0: e2mgr.GetNodesRequest
	(*GetNodesResponse)(nil),                // 1: e2mgr.GetNodesResponse
	(*GetNodeRequest)(nil),                  // 2: e2mgr.GetNodeRequest
	(*GetNodeResponse)(nil),                 // 3: e2mgr.GetNodeResponse
	(*UpdateNodeConfigurationRequest)(nil),  // 4: e2mgr.UpdateNodeConfigurationRequest
	(*UpdateNodeConfigurationResponse)(nil), // 5: e2mgr.UpdateNodeConfigurationResponse
	(*DeleteNodeRequest)(nil),               // 6: e2mgr.DeleteNodeRequest
	(*DeleteNodeResponse)(nil),              // 7: e2mgr.DeleteNodeResponse
	(*GetNodeHealthRequest)(nil),            // 8: e2mgr.GetNodeHealthRequest
	(*GetNodeHealthResponse)(nil),           // 9: e2mgr.GetNodeHealthResponse
	(*GetStatsRequest)(nil),                 // 10: e2mgr.GetStatsRequest
	(*GetStatsResponse)(nil),                // 11: e2mgr.GetStatsResponse
	(*E2SetupRequest)(nil),                  // 12: e2mgr.E2SetupRequest
	(*E2SetupResponse)(nil),                 // 13: e2mgr.E2SetupResponse
	(*ConfigurationUpdateRequest)(nil),      // 14: e2mgr.ConfigurationUpdateRequest
	(*ConfigurationUpdateResponse)(nil),     // 15: e2mgr.ConfigurationUpdateResponse
	(*ResetRequest)(nil),                    // 16: e2mgr.ResetRequest
	(*ResetResponse)(nil),                   // 17: e2mgr.ResetResponse
	(*E2Node)(nil),                          // 18: e2mgr.E2Node
	(*GlobalE2NodeID)(nil),                  // 19: e2mgr.GlobalE2NodeID
	(*ServiceModel)(nil),                    // 20: e2mgr.ServiceModel
	(*RANFunction)(nil),                     // 21: e2mgr.RANFunction
	(*RANFunctionAccepted)(nil),             // 22: e2mgr.RANFunctionAccepted
	(*RANFunctionRejected)(nil),             // 23: e2mgr.RANFunctionRejected
	(*E2NodeComponentConfig)(nil),           // 24: e2mgr.E2NodeComponentConfig
	(*SubscriptionInfo)(nil),                // 25: e2mgr.SubscriptionInfo
	(*E2SetupRequestData)(nil),              // 26: e2mgr.E2SetupRequestData
	(*NodeConfiguration)(nil),               // 27: e2mgr.NodeConfiguration
	(*NodeHealth)(nil),                      // 28: e2mgr.NodeHealth
	(*E2ManagerStats)(nil),                  // 29: e2mgr.E2ManagerStats
	nil,                                     // 30: e2mgr.NodeConfiguration.ParametersEntry
	nil,                                     // 31: e2mgr.E2ManagerStats.NodesByTypeEntry
	nil,                                     // 32: e2mgr.E2ManagerStats.NodesByStatusEntry
	(*timestamppb.Timestamp)(nil),           // 33: google.protobuf.Timestamp
}
var file_api_proto_e2mgr_e2mgr_proto_depIdxs = []int32{
	18, // 0: e2mgr.GetNodesResponse.nodes:type_name -> e2mgr.E2Node
	18, // 1: e2mgr.GetNodeResponse.node:type_name -> e2mgr.E2Node
	27, // 2: e2mgr.UpdateNodeConfigurationRequest.configuration:type_name -> e2mgr.NodeConfiguration
	28, // 3: e2mgr.GetNodeHealthResponse.health:type_name -> e2mgr.NodeHealth
	29, // 4: e2mgr.GetStatsResponse.stats:type_name -> e2mgr.E2ManagerStats
	19, // 5: e2mgr.E2SetupRequest.global_e2_node_id:type_name -> e2mgr.GlobalE2NodeID
	21, // 6: e2mgr.E2SetupRequest.ran_functions:type_name -> e2mgr.RANFunction
	24, // 7: e2mgr.E2SetupRequest.e2_node_component_config_add_list:type_name -> e2mgr.E2NodeComponentConfig
	22, // 8: e2mgr.E2SetupResponse.ran_functions_accepted:type_name -> e2mgr.RANFunctionAccepted
	23, // 9: e2mgr.E2SetupResponse.ran_functions_rejected:type_name -> e2mgr.RANFunctionRejected
	24, // 10: e2mgr.ConfigurationUpdateRequest.config_update_list:type_name -> e2mgr.E2NodeComponentConfig
	19, // 11: e2mgr.E2Node.global_e2_node_id:type_name -> e2mgr.GlobalE2NodeID
	20, // 12: e2mgr.E2Node.service_models:type_name -> e2mgr.ServiceModel
	21, // 13: e2mgr.E2Node.ran_functions:type_name -> e2mgr.RANFunction
	33, // 14: e2mgr.E2Node.last_update:type_name -> google.protobuf.Timestamp
	25, // 15: e2mgr.E2Node.subscriptions:type_name -> e2mgr.SubscriptionInfo
	26, // 16: e2mgr.E2Node.setup_request:type_name -> e2mgr.E2SetupRequestData
	21, // 17: e2mgr.ServiceModel.functions:type_name -> e2mgr.RANFunction
	19, // 18: e2mgr.E2SetupRequestData.global_e2_node_id:type_name -> e2mgr.GlobalE2NodeID
	21, // 19: e2mgr.E2SetupRequestData.ran_functions:type_name -> e2mgr.RANFunction
	24, // 20: e2mgr.E2SetupRequestData.e2_node_component_config_add_list:type_name -> e2mgr.E2NodeComponentConfig
	30, // 21: e2mgr.NodeConfiguration.parameters:type_name -> e2mgr.NodeConfiguration.ParametersEntry
	24, // 22: e2mgr.NodeConfiguration.component_configs:type_name -> e2mgr.E2NodeComponentConfig
	33, // 23: e2mgr.NodeHealth.last_health_check:type_name -> google.protobuf.Timestamp
	31, // 24: e2mgr.E2ManagerStats.nodes_by_type:type_name -> e2mgr.E2ManagerStats.NodesByTypeEntry
	32, // 25: e2mgr.E2ManagerStats.nodes_by_status:type_name -> e2mgr.E2ManagerStats.NodesByStatusEntry
	33, // 26: e2mgr.E2ManagerStats.last_updated:type_name -> google.protobuf.Timestamp
	0,  // 27: e2mgr.E2Manager.GetNodes:input_type -> e2mgr.GetNodesRequest
	2,  // 28: e2mgr.E2Manager.GetNode:input_type -> e2mgr.GetNodeRequest
	4,  // 29: e2mgr.E2Manager.UpdateNodeConfiguration:input_type -> e2mgr.UpdateNodeConfigurationRequest
	6,  // 30: e2mgr.E2Manager.DeleteNode:input_type -> e2mgr.DeleteNodeRequest
	8,  // 31: e2mgr.E2Manager.GetNodeHealth:input_type -> e2mgr.GetNodeHealthRequest
	10, // 32: e2mgr.E2Manager.GetStats:input_type -> e2mgr.GetStatsRequest
	12, // 33: e2mgr.E2Manager.HandleE2Setup:input_type -> e2mgr.E2SetupRequest
	14, // 34: e2mgr.E2Manager.HandleConfigurationUpdate:input_type -> e2mgr.ConfigurationUpdateRequest
	16, // 35: e2mgr.E2Manager.HandleReset:input_type -> e2mgr.ResetRequest
	1,  // 36: e2mgr.E2Manager.GetNodes:output_type -> e2mgr.GetNodesResponse
	3,  // 37: e2mgr.E2Manager.GetNode:output_type -> e2mgr.GetNodeResponse
	5,  // 38: e2mgr.E2Manager.UpdateNodeConfiguration:output_type -> e2mgr.UpdateNodeConfigurationResponse
	7,  // 39: e2mgr.E2Manager.DeleteNode:output_type -> e2mgr.DeleteNodeResponse
	9,  // 40: e2mgr.E2Manager.GetNodeHealth:output_type -> e2mgr.GetNodeHealthResponse
	11, // 41: e2mgr.E2Manager.GetStats:output_type -> e2mgr.GetStatsResponse
	13, // 42: e2mgr.E2Manager.HandleE2Setup:output_type -> e2mgr.E2SetupResponse
	15, // 43: e2mgr.E2Manager.HandleConfigurationUpdate:output_type -> e2mgr.ConfigurationUpdateResponse
	17, // 44: e2mgr.E2Manager.HandleReset:output_type -> e2mgr.ResetResponse
	36, // [36:45] is the sub-list for method output_type
	27, // [27:36] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_api_proto_e2mgr_e2mgr_proto_init() }
func file_api_proto_e2mgr_e2mgr_proto_init() {
	if File_api_proto_e2mgr_e2mgr_proto != nil {
		return
	}
	file_api_proto_e2mgr_e2mgr_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_e2mgr_e2mgr_proto_rawDesc), len(file_api_proto_e2mgr_e2mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_e2mgr_e2mgr_proto_goTypes,
		DependencyIndexes: file_api_proto_e2mgr_e2mgr_proto_depIdxs,
		MessageInfos:      file_api_proto_e2mgr_e2mgr_proto_msgTypes,
	}.Build()
	File_api_proto_e2mgr_e2mgr_proto = out.File
	file_api_proto_e2mgr_e2mgr_proto_goTypes = nil
	file_api_proto_e2mgr_e2mgr_proto_depIdxs = nil
}
