// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/e2mgr/e2mgr.proto

package e2mgr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// E2ManagerClient is the client API for E2Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type E2ManagerClient interface {
	// Node management operations
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	UpdateNodeConfiguration(ctx context.Context, in *UpdateNodeConfigurationRequest, opts ...grpc.CallOption) (*UpdateNodeConfigurationResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	// Health and statistics
	GetNodeHealth(ctx context.Context, in *GetNodeHealthRequest, opts ...grpc.CallOption) (*GetNodeHealthResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// Setup procedures
	HandleE2Setup(ctx context.Context, in *E2SetupRequest, opts ...grpc.CallOption) (*E2SetupResponse, error)
	HandleConfigurationUpdate(ctx context.Context, in *ConfigurationUpdateRequest, opts ...grpc.CallOption) (*ConfigurationUpdateResponse, error)
	HandleReset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
}

type e2ManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewE2ManagerClient(cc grpc.ClientConnInterface) E2ManagerClient {
	return &e2ManagerClient{cc}
}

func (c *e2ManagerClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/GetNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) UpdateNodeConfiguration(ctx context.Context, in *UpdateNodeConfigurationRequest, opts ...grpc.CallOption) (*UpdateNodeConfigurationResponse, error) {
	out := new(UpdateNodeConfigurationResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/UpdateNodeConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	out := new(DeleteNodeResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) GetNodeHealth(ctx context.Context, in *GetNodeHealthRequest, opts ...grpc.CallOption) (*GetNodeHealthResponse, error) {
	out := new(GetNodeHealthResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/GetNodeHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) HandleE2Setup(ctx context.Context, in *E2SetupRequest, opts ...grpc.CallOption) (*E2SetupResponse, error) {
	out := new(E2SetupResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/HandleE2Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) HandleConfigurationUpdate(ctx context.Context, in *ConfigurationUpdateRequest, opts ...grpc.CallOption) (*ConfigurationUpdateResponse, error) {
	out := new(ConfigurationUpdateResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/HandleConfigurationUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2ManagerClient) HandleReset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, "/e2mgr.E2Manager/HandleReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// E2ManagerServer is the server API for E2Manager service.
// All implementations must embed UnimplementedE2ManagerServer
// for forward compatibility
type E2ManagerServer interface {
	// Node management operations
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	UpdateNodeConfiguration(context.Context, *UpdateNodeConfigurationRequest) (*UpdateNodeConfigurationResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	// Health and statistics
	GetNodeHealth(context.Context, *GetNodeHealthRequest) (*GetNodeHealthResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// Setup procedures
	HandleE2Setup(context.Context, *E2SetupRequest) (*E2SetupResponse, error)
	HandleConfigurationUpdate(context.Context, *ConfigurationUpdateRequest) (*ConfigurationUpdateResponse, error)
	HandleReset(context.Context, *ResetRequest) (*ResetResponse, error)
	mustEmbedUnimplementedE2ManagerServer()
}

// UnimplementedE2ManagerServer must be embedded to have forward compatible implementations.
type UnimplementedE2ManagerServer struct {
}

func (UnimplementedE2ManagerServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedE2ManagerServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedE2ManagerServer) UpdateNodeConfiguration(context.Context, *UpdateNodeConfigurationRequest) (*UpdateNodeConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeConfiguration not implemented")
}
func (UnimplementedE2ManagerServer) DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedE2ManagerServer) GetNodeHealth(context.Context, *GetNodeHealthRequest) (*GetNodeHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeHealth not implemented")
}
func (UnimplementedE2ManagerServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedE2ManagerServer) HandleE2Setup(context.Context, *E2SetupRequest) (*E2SetupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleE2Setup not implemented")
}
func (UnimplementedE2ManagerServer) HandleConfigurationUpdate(context.Context, *ConfigurationUpdateRequest) (*ConfigurationUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleConfigurationUpdate not implemented")
}
func (UnimplementedE2ManagerServer) HandleReset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleReset not implemented")
}
func (UnimplementedE2ManagerServer) mustEmbedUnimplementedE2ManagerServer() {}

// UnsafeE2ManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to E2ManagerServer will
// result in compilation errors.
type UnsafeE2ManagerServer interface {
	mustEmbedUnimplementedE2ManagerServer()
}

func RegisterE2ManagerServer(s grpc.ServiceRegistrar, srv E2ManagerServer) {
	s.RegisterService(&E2Manager_ServiceDesc, srv)
}

func _E2Manager_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2ManagerServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2mgr.E2Manager/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2ManagerServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Additional handler functions would be here in real implementation

// E2Manager_ServiceDesc is the grpc.ServiceDesc for E2Manager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var E2Manager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "e2mgr.E2Manager",
	HandlerType: (*E2ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _E2Manager_GetNodes_Handler,
		},
		// Additional method descriptors would be here in real implementation
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/e2mgr/e2mgr.proto",
}