// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/submgr/submgr.proto

package submgr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriptionManagerClient is the client API for SubscriptionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionManagerClient interface {
	// Subscription lifecycle operations
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
	GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*GetSubscriptionsResponse, error)
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error)
	UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	// Indication handling
	GetIndications(ctx context.Context, in *GetIndicationsRequest, opts ...grpc.CallOption) (*GetIndicationsResponse, error)
	StreamIndications(ctx context.Context, in *StreamIndicationsRequest, opts ...grpc.CallOption) (SubscriptionManager_StreamIndicationsClient, error)
	// Statistics and monitoring
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	GetSubscriptionHealth(ctx context.Context, in *GetSubscriptionHealthRequest, opts ...grpc.CallOption) (*GetSubscriptionHealthResponse, error)
}

type subscriptionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionManagerClient(cc grpc.ClientConnInterface) SubscriptionManagerClient {
	return &subscriptionManagerClient{cc}
}

func (c *subscriptionManagerClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/CreateSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*GetSubscriptionsResponse, error) {
	out := new(GetSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/GetSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error) {
	out := new(GetSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/GetSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error) {
	out := new(UpdateSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/UpdateSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/DeleteSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) GetIndications(ctx context.Context, in *GetIndicationsRequest, opts ...grpc.CallOption) (*GetIndicationsResponse, error) {
	out := new(GetIndicationsResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/GetIndications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) StreamIndications(ctx context.Context, in *StreamIndicationsRequest, opts ...grpc.CallOption) (SubscriptionManager_StreamIndicationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionManager_ServiceDesc.Streams[0], "/submgr.SubscriptionManager/StreamIndications", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionManagerStreamIndicationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionManager_StreamIndicationsClient interface {
	Recv() (*IndicationMessage, error)
	grpc.ClientStream
}

type subscriptionManagerStreamIndicationsClient struct {
	grpc.ClientStream
}

func (x *subscriptionManagerStreamIndicationsClient) Recv() (*IndicationMessage, error) {
	m := new(IndicationMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionManagerClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionManagerClient) GetSubscriptionHealth(ctx context.Context, in *GetSubscriptionHealthRequest, opts ...grpc.CallOption) (*GetSubscriptionHealthResponse, error) {
	out := new(GetSubscriptionHealthResponse)
	err := c.cc.Invoke(ctx, "/submgr.SubscriptionManager/GetSubscriptionHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionManagerServer is the server API for SubscriptionManager service.
// All implementations must embed UnimplementedSubscriptionManagerServer
// for forward compatibility
type SubscriptionManagerServer interface {
	// Subscription lifecycle operations
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*GetSubscriptionsResponse, error)
	GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error)
	UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionResponse, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	// Indication handling
	GetIndications(context.Context, *GetIndicationsRequest) (*GetIndicationsResponse, error)
	StreamIndications(*StreamIndicationsRequest, SubscriptionManager_StreamIndicationsServer) error
	// Statistics and monitoring
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	GetSubscriptionHealth(context.Context, *GetSubscriptionHealthRequest) (*GetSubscriptionHealthResponse, error)
	mustEmbedUnimplementedSubscriptionManagerServer()
}

// SubscriptionManager_StreamIndicationsServer is the server API for StreamIndications streaming method.
type SubscriptionManager_StreamIndicationsServer interface {
	Send(*IndicationMessage) error
	grpc.ServerStream
}

type subscriptionManagerStreamIndicationsServer struct {
	grpc.ServerStream
}

func (x *subscriptionManagerStreamIndicationsServer) Send(m *IndicationMessage) error {
	return x.ServerStream.SendMsg(m)
}

// UnimplementedSubscriptionManagerServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriptionManagerServer struct {
}

func (UnimplementedSubscriptionManagerServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedSubscriptionManagerServer) GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*GetSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedSubscriptionManagerServer) GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedSubscriptionManagerServer) UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedSubscriptionManagerServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedSubscriptionManagerServer) GetIndications(context.Context, *GetIndicationsRequest) (*GetIndicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndications not implemented")
}
func (UnimplementedSubscriptionManagerServer) StreamIndications(*StreamIndicationsRequest, SubscriptionManager_StreamIndicationsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamIndications not implemented")
}
func (UnimplementedSubscriptionManagerServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedSubscriptionManagerServer) GetSubscriptionHealth(context.Context, *GetSubscriptionHealthRequest) (*GetSubscriptionHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptionHealth not implemented")
}
func (UnimplementedSubscriptionManagerServer) mustEmbedUnimplementedSubscriptionManagerServer() {}

// UnsafeSubscriptionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionManagerServer will
// result in compilation errors.
type UnsafeSubscriptionManagerServer interface {
	mustEmbedUnimplementedSubscriptionManagerServer()
}

func RegisterSubscriptionManagerServer(s grpc.ServiceRegistrar, srv SubscriptionManagerServer) {
	s.RegisterService(&SubscriptionManager_ServiceDesc, srv)
}

func _SubscriptionManager_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/CreateSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/GetSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).GetSubscriptions(ctx, req.(*GetSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/GetSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).GetSubscription(ctx, req.(*GetSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/UpdateSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).UpdateSubscription(ctx, req.(*UpdateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/DeleteSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_GetIndications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).GetIndications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/GetIndications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).GetIndications(ctx, req.(*GetIndicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_StreamIndications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamIndicationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionManagerServer).StreamIndications(m, &subscriptionManagerStreamIndicationsServer{stream})
}

func _SubscriptionManager_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionManager_GetSubscriptionHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionManagerServer).GetSubscriptionHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submgr.SubscriptionManager/GetSubscriptionHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionManagerServer).GetSubscriptionHealth(ctx, req.(*GetSubscriptionHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionManager_ServiceDesc is the grpc.ServiceDesc for SubscriptionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "submgr.SubscriptionManager",
	HandlerType: (*SubscriptionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubscription",
			Handler:    _SubscriptionManager_CreateSubscription_Handler,
		},
		{
			MethodName: "GetSubscriptions",
			Handler:    _SubscriptionManager_GetSubscriptions_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _SubscriptionManager_GetSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _SubscriptionManager_UpdateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _SubscriptionManager_DeleteSubscription_Handler,
		},
		{
			MethodName: "GetIndications",
			Handler:    _SubscriptionManager_GetIndications_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _SubscriptionManager_GetStats_Handler,
		},
		{
			MethodName: "GetSubscriptionHealth",
			Handler:    _SubscriptionManager_GetSubscriptionHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIndications",
			Handler:       _SubscriptionManager_StreamIndications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/submgr/submgr.proto",
}