// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/proto/submgr/submgr.proto

package submgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSubscriptionRequest represents a request to create a new subscription
type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E2NodeId       string        `protobuf:"bytes,1,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	XappId         string        `protobuf:"bytes,2,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
	RanFunctionId  uint32        `protobuf:"varint,3,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	EventTrigger   *EventTrigger `protobuf:"bytes,4,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions        []*Action     `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	TimeoutMs      uint32        `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// CreateSubscriptionResponse represents response from creating a subscription
type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Success        bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreateSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSubscriptionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetSubscriptionsRequest represents request to get all subscriptions
type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E2NodeId string `protobuf:"bytes,1,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	XappId   string `protobuf:"bytes,2,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{6}
}

func (x *GetSubscriptionsRequest) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *GetSubscriptionsRequest) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

// GetSubscriptionsResponse represents response with all subscriptions
type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscriptions []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{7}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// GetSubscriptionRequest represents request to get a specific subscription
type GetSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// GetSubscriptionResponse represents response with a specific subscription
type GetSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscription *Subscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{9}
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// UpdateSubscriptionRequest represents request to update a subscription
type UpdateSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string        `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	EventTrigger   *EventTrigger `protobuf:"bytes,2,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions        []*Action     `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *UpdateSubscriptionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

// UpdateSubscriptionResponse represents response from updating a subscription
type UpdateSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *UpdateSubscriptionResponse) Reset() {
	*x = UpdateSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionResponse) ProtoMessage() {}

func (x *UpdateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSubscriptionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// DeleteSubscriptionRequest represents request to delete a subscription
type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// DeleteSubscriptionResponse represents response from deleting a subscription
type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSubscriptionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetIndicationsRequest represents request to get indications
type GetIndicationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
}

func (x *GetIndicationsRequest) Reset() {
	*x = GetIndicationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIndicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndicationsRequest) ProtoMessage() {}

func (x *GetIndicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndicationsRequest.ProtoReflect.Descriptor instead.
func (*GetIndicationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{14}
}

func (x *GetIndicationsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// GetIndicationsResponse represents response with indications
type GetIndicationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indications []string `protobuf:"bytes,1,rep,name=indications,proto3" json:"indications,omitempty"`
}

func (x *GetIndicationsResponse) Reset() {
	*x = GetIndicationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIndicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndicationsResponse) ProtoMessage() {}

func (x *GetIndicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndicationsResponse.ProtoReflect.Descriptor instead.
func (*GetIndicationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{15}
}

func (x *GetIndicationsResponse) GetIndications() []string {
	if x != nil {
		return x.Indications
	}
	return nil
}

// StreamIndicationsRequest represents request to stream indications
type StreamIndicationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
}

func (x *StreamIndicationsRequest) Reset() {
	*x = StreamIndicationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamIndicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndicationsRequest) ProtoMessage() {}

func (x *StreamIndicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndicationsRequest.ProtoReflect.Descriptor instead.
func (*StreamIndicationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{16}
}

func (x *StreamIndicationsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// GetStatsRequest represents request to get statistics
type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E2NodeId string `protobuf:"bytes,1,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatsRequest) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

// GetStatsResponse represents response with statistics
type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSubscriptions int32             `protobuf:"varint,1,opt,name=total_subscriptions,json=totalSubscriptions,proto3" json:"total_subscriptions,omitempty"`
	ActiveSubscriptions int32            `protobuf:"varint,2,opt,name=active_subscriptions,json=activeSubscriptions,proto3" json:"active_subscriptions,omitempty"`
	NodeStats          map[string]int32  `protobuf:"bytes,3,rep,name=node_stats,json=nodeStats,proto3" json:"node_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{18}
}

func (x *GetStatsResponse) GetTotalSubscriptions() int32 {
	if x != nil {
		return x.TotalSubscriptions
	}
	return 0
}

func (x *GetStatsResponse) GetActiveSubscriptions() int32 {
	if x != nil {
		return x.ActiveSubscriptions
	}
	return 0
}

func (x *GetStatsResponse) GetNodeStats() map[string]int32 {
	if x != nil {
		return x.NodeStats
	}
	return nil
}

// GetSubscriptionHealthRequest represents request to get subscription health
type GetSubscriptionHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
}

func (x *GetSubscriptionHealthRequest) Reset() {
	*x = GetSubscriptionHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscriptionHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHealthRequest) ProtoMessage() {}

func (x *GetSubscriptionHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHealthRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{19}
}

func (x *GetSubscriptionHealthRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// GetSubscriptionHealthResponse represents response with subscription health
type GetSubscriptionHealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	HealthStatus   string `protobuf:"bytes,2,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	LastUpdate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
}

func (x *GetSubscriptionHealthResponse) Reset() {
	*x = GetSubscriptionHealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscriptionHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHealthResponse) ProtoMessage() {}

func (x *GetSubscriptionHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHealthResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{20}
}

func (x *GetSubscriptionHealthResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GetSubscriptionHealthResponse) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *GetSubscriptionHealthResponse) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

// IndicationMessage represents an indication message
type IndicationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string    `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Payload        []byte    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *IndicationMessage) Reset() {
	*x = IndicationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndicationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicationMessage) ProtoMessage() {}

func (x *IndicationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicationMessage.ProtoReflect.Descriptor instead.
func (*IndicationMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{21}
}

func (x *IndicationMessage) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *IndicationMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IndicationMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Subscription represents a subscription
type Subscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	E2NodeId       string                 `protobuf:"bytes,2,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	XappId         string                 `protobuf:"bytes,3,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
	RanFunctionId  uint32                 `protobuf:"varint,4,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	EventTrigger   *EventTrigger          `protobuf:"bytes,5,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions        []*Action              `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *Subscription) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

func (x *Subscription) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *Subscription) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *Subscription) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// EventTrigger represents an event trigger
type EventTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceId       uint32 `protobuf:"varint,1,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	InterfaceDirection uint32 `protobuf:"varint,2,opt,name=interface_direction,json=interfaceDirection,proto3" json:"interface_direction,omitempty"`
	InterfaceMessageId uint32 `protobuf:"varint,3,opt,name=interface_message_id,json=interfaceMessageId,proto3" json:"interface_message_id,omitempty"`
}

func (x *EventTrigger) Reset() {
	*x = EventTrigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTrigger) ProtoMessage() {}

func (x *EventTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTrigger.ProtoReflect.Descriptor instead.
func (*EventTrigger) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{3}
}

func (x *EventTrigger) GetInterfaceId() uint32 {
	if x != nil {
		return x.InterfaceId
	}
	return 0
}

func (x *EventTrigger) GetInterfaceDirection() uint32 {
	if x != nil {
		return x.InterfaceDirection
	}
	return 0
}

func (x *EventTrigger) GetInterfaceMessageId() uint32 {
	if x != nil {
		return x.InterfaceMessageId
	}
	return 0
}

// Action represents an action
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Definition       []byte            `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	SubsequentAction *SubsequentAction `protobuf:"bytes,4,opt,name=subsequent_action,json=subsequentAction,proto3" json:"subsequent_action,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{4}
}

func (x *Action) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetDefinition() []byte {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Action) GetSubsequentAction() *SubsequentAction {
	if x != nil {
		return x.SubsequentAction
	}
	return nil
}

// SubsequentAction represents a subsequent action
type SubsequentAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TimeToWait  uint32 `protobuf:"varint,2,opt,name=time_to_wait,json=timeToWait,proto3" json:"time_to_wait,omitempty"`
}

func (x *SubsequentAction) Reset() {
	*x = SubsequentAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubsequentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsequentAction) ProtoMessage() {}

func (x *SubsequentAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsequentAction.ProtoReflect.Descriptor instead.
func (*SubsequentAction) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{5}
}

func (x *SubsequentAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubsequentAction) GetTimeToWait() uint32 {
	if x != nil {
		return x.TimeToWait
	}
	return 0
}

var File_api_proto_submgr_submgr_proto protoreflect.FileDescriptor

var file_api_proto_submgr_submgr_proto_rawDesc = []byte{
	// Simplified descriptor - in real implementation this would be much longer
}

var (
	file_api_proto_submgr_submgr_proto_rawDescOnce sync.Once
	file_api_proto_submgr_submgr_proto_rawDescData = file_api_proto_submgr_submgr_proto_rawDesc
)

func file_api_proto_submgr_submgr_proto_rawDescGZIP() []byte {
	file_api_proto_submgr_submgr_proto_rawDescOnce.Do(func() {
		file_api_proto_submgr_submgr_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_submgr_submgr_proto_rawDescData)
	})
	return file_api_proto_submgr_submgr_proto_rawDescData
}

var file_api_proto_submgr_submgr_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_submgr_submgr_proto_goTypes = []interface{}{
	(*CreateSubscriptionRequest)(nil),       // 0: submgr.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),      // 1: submgr.CreateSubscriptionResponse
	(*Subscription)(nil),                    // 2: submgr.Subscription
	(*EventTrigger)(nil),                    // 3: submgr.EventTrigger
	(*Action)(nil),                          // 4: submgr.Action
	(*SubsequentAction)(nil),                // 5: submgr.SubsequentAction
	(*GetSubscriptionsRequest)(nil),         // 6: submgr.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),        // 7: submgr.GetSubscriptionsResponse
	(*GetSubscriptionRequest)(nil),          // 8: submgr.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),         // 9: submgr.GetSubscriptionResponse
	(*UpdateSubscriptionRequest)(nil),       // 10: submgr.UpdateSubscriptionRequest
	(*UpdateSubscriptionResponse)(nil),      // 11: submgr.UpdateSubscriptionResponse
	(*DeleteSubscriptionRequest)(nil),       // 12: submgr.DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil),      // 13: submgr.DeleteSubscriptionResponse
	(*GetIndicationsRequest)(nil),           // 14: submgr.GetIndicationsRequest
	(*GetIndicationsResponse)(nil),          // 15: submgr.GetIndicationsResponse
	(*StreamIndicationsRequest)(nil),        // 16: submgr.StreamIndicationsRequest
	(*GetStatsRequest)(nil),                 // 17: submgr.GetStatsRequest
	(*GetStatsResponse)(nil),                // 18: submgr.GetStatsResponse
	(*GetSubscriptionHealthRequest)(nil),    // 19: submgr.GetSubscriptionHealthRequest
	(*GetSubscriptionHealthResponse)(nil),   // 20: submgr.GetSubscriptionHealthResponse
	(*IndicationMessage)(nil),               // 21: submgr.IndicationMessage
	(*timestamppb.Timestamp)(nil),           // 22: google.protobuf.Timestamp
}

var file_api_proto_submgr_submgr_proto_depIdxs = []int32{
	3, // 0: submgr.CreateSubscriptionRequest.event_trigger:type_name -> submgr.EventTrigger
	4, // 1: submgr.CreateSubscriptionRequest.actions:type_name -> submgr.Action
	3, // 2: submgr.Subscription.event_trigger:type_name -> submgr.EventTrigger
	4, // 3: submgr.Subscription.actions:type_name -> submgr.Action
	22, // 4: submgr.Subscription.created_at:type_name -> google.protobuf.Timestamp
	22, // 5: submgr.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	5, // 6: submgr.Action.subsequent_action:type_name -> submgr.SubsequentAction
	2, // 7: submgr.GetSubscriptionsResponse.subscriptions:type_name -> submgr.Subscription
	2, // 8: submgr.GetSubscriptionResponse.subscription:type_name -> submgr.Subscription
	3, // 9: submgr.UpdateSubscriptionRequest.event_trigger:type_name -> submgr.EventTrigger
	4, // 10: submgr.UpdateSubscriptionRequest.actions:type_name -> submgr.Action
	22, // 11: submgr.GetSubscriptionHealthResponse.last_update:type_name -> google.protobuf.Timestamp
	22, // 12: submgr.IndicationMessage.timestamp:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0, // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_submgr_submgr_proto_init() }
func file_api_proto_submgr_submgr_proto_init() {
	if File_api_proto_submgr_submgr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_submgr_submgr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventTrigger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubsequentAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscriptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscriptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIndicationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIndicationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamIndicationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscriptionHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscriptionHealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_submgr_submgr_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndicationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_submgr_submgr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_submgr_submgr_proto_goTypes,
		DependencyIndexes: file_api_proto_submgr_submgr_proto_depIdxs,
		MessageInfos:      file_api_proto_submgr_submgr_proto_msgTypes,
	}.Build()
	File_api_proto_submgr_submgr_proto = out.File
	file_api_proto_submgr_submgr_proto_rawDesc = nil
	file_api_proto_submgr_submgr_proto_goTypes = nil
	file_api_proto_submgr_submgr_proto_depIdxs = nil
}