// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/proto/submgr/submgr.proto

package submgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSubscriptionRequest represents a request to create a new subscription
type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E2NodeId       string        `protobuf:"bytes,1,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	XappId         string        `protobuf:"bytes,2,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
	RanFunctionId  uint32        `protobuf:"varint,3,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	EventTrigger   *EventTrigger `protobuf:"bytes,4,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions        []*Action     `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	TimeoutMs      uint32        `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// CreateSubscriptionResponse represents the response to a subscription creation request
type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Success        bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message        string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreateSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Subscription represents a subscription in the system
type Subscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	E2NodeId       string                 `protobuf:"bytes,2,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	XappId         string                 `protobuf:"bytes,3,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
	RanFunctionId  uint32                 `protobuf:"varint,4,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	EventTrigger   *EventTrigger          `protobuf:"bytes,5,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions        []*Action              `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *Subscription) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

func (x *Subscription) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *Subscription) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *Subscription) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// EventTrigger represents an event trigger for subscriptions
type EventTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Definition []byte  `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	PeriodMs   *uint32 `protobuf:"varint,3,opt,name=period_ms,json=periodMs,proto3,oneof" json:"period_ms,omitempty"`
}

func (x *EventTrigger) Reset() {
	*x = EventTrigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTrigger) ProtoMessage() {}

func (x *EventTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTrigger.ProtoReflect.Descriptor instead.
func (*EventTrigger) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{3}
}

func (x *EventTrigger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventTrigger) GetDefinition() []byte {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *EventTrigger) GetPeriodMs() uint32 {
	if x != nil && x.PeriodMs != nil {
		return *x.PeriodMs
	}
	return 0
}

// Action represents an action in a subscription
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Definition       []byte            `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	SubsequentAction *SubsequentAction `protobuf:"bytes,4,opt,name=subsequent_action,json=subsequentAction,proto3,oneof" json:"subsequent_action,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{4}
}

func (x *Action) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetDefinition() []byte {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Action) GetSubsequentAction() *SubsequentAction {
	if x != nil {
		return x.SubsequentAction
	}
	return nil
}

// SubsequentAction represents a subsequent action
type SubsequentAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TimeToWait  uint32 `protobuf:"varint,2,opt,name=time_to_wait,json=timeToWait,proto3" json:"time_to_wait,omitempty"`
}

func (x *SubsequentAction) Reset() {
	*x = SubsequentAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_submgr_submgr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubsequentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsequentAction) ProtoMessage() {}

func (x *SubsequentAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsequentAction.ProtoReflect.Descriptor instead.
func (*SubsequentAction) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{5}
}

func (x *SubsequentAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubsequentAction) GetTimeToWait() uint32 {
	if x != nil {
		return x.TimeToWait
	}
	return 0
}

var File_api_proto_submgr_submgr_proto protoreflect.FileDescriptor

var file_api_proto_submgr_submgr_proto_rawDesc = []byte{
	// Simplified descriptor - in real implementation this would be much longer
}

var (
	file_api_proto_submgr_submgr_proto_rawDescOnce sync.Once
	file_api_proto_submgr_submgr_proto_rawDescData = file_api_proto_submgr_submgr_proto_rawDesc
)

func file_api_proto_submgr_submgr_proto_rawDescGZIP() []byte {
	file_api_proto_submgr_submgr_proto_rawDescOnce.Do(func() {
		file_api_proto_submgr_submgr_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_submgr_submgr_proto_rawDescData)
	})
	return file_api_proto_submgr_submgr_proto_rawDescData
}

var file_api_proto_submgr_submgr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_submgr_submgr_proto_goTypes = []interface{}{
	(*CreateSubscriptionRequest)(nil),  // 0: submgr.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil), // 1: submgr.CreateSubscriptionResponse
	(*Subscription)(nil),               // 2: submgr.Subscription
	(*EventTrigger)(nil),               // 3: submgr.EventTrigger
	(*Action)(nil),                     // 4: submgr.Action
	(*SubsequentAction)(nil),           // 5: submgr.SubsequentAction
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}

var file_api_proto_submgr_submgr_proto_depIdxs = []int32{
	3, // 0: submgr.CreateSubscriptionRequest.event_trigger:type_name -> submgr.EventTrigger
	4, // 1: submgr.CreateSubscriptionRequest.actions:type_name -> submgr.Action
	3, // 2: submgr.Subscription.event_trigger:type_name -> submgr.EventTrigger
	4, // 3: submgr.Subscription.actions:type_name -> submgr.Action
	6, // 4: submgr.Subscription.created_at:type_name -> google.protobuf.Timestamp
	6, // 5: submgr.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	5, // 6: submgr.Action.subsequent_action:type_name -> submgr.SubsequentAction
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_submgr_submgr_proto_init() }
func file_api_proto_submgr_submgr_proto_init() {
	if File_api_proto_submgr_submgr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_submgr_submgr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		// Additional message type exporters would be here in real implementation
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_submgr_submgr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_submgr_submgr_proto_goTypes,
		DependencyIndexes: file_api_proto_submgr_submgr_proto_depIdxs,
		MessageInfos:      file_api_proto_submgr_submgr_proto_msgTypes,
	}.Build()
	File_api_proto_submgr_submgr_proto = out.File
	file_api_proto_submgr_submgr_proto_rawDesc = nil
	file_api_proto_submgr_submgr_proto_goTypes = nil
	file_api_proto_submgr_submgr_proto_depIdxs = nil
}