// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.1
// source: api/proto/submgr/submgr.proto

package submgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages for subscription operations
type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	E2NodeId      string                 `protobuf:"bytes,1,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	XappId        string                 `protobuf:"bytes,2,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
	RanFunctionId uint32                 `protobuf:"varint,3,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	EventTrigger  *EventTrigger          `protobuf:"bytes,4,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions       []*Action              `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type CreateSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreateSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	E2NodeId      *string                `protobuf:"bytes,1,opt,name=e2_node_id,json=e2NodeId,proto3,oneof" json:"e2_node_id,omitempty"`
	XappId        *string                `protobuf:"bytes,2,opt,name=xapp_id,json=xappId,proto3,oneof" json:"xapp_id,omitempty"`
	RanFunctionId *uint32                `protobuf:"varint,3,opt,name=ran_function_id,json=ranFunctionId,proto3,oneof" json:"ran_function_id,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Limit         *uint32                `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint32                `protobuf:"varint,6,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubscriptionsRequest) GetE2NodeId() string {
	if x != nil && x.E2NodeId != nil {
		return *x.E2NodeId
	}
	return ""
}

func (x *GetSubscriptionsRequest) GetXappId() string {
	if x != nil && x.XappId != nil {
		return *x.XappId
	}
	return ""
}

func (x *GetSubscriptionsRequest) GetRanFunctionId() uint32 {
	if x != nil && x.RanFunctionId != nil {
		return *x.RanFunctionId
	}
	return 0
}

func (x *GetSubscriptionsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetSubscriptionsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetSubscriptionsRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *GetSubscriptionsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type UpdateSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	EventTrigger   *EventTrigger          `protobuf:"bytes,2,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions        []*Action              `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *UpdateSubscriptionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type UpdateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionResponse) Reset() {
	*x = UpdateSubscriptionResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionResponse) ProtoMessage() {}

func (x *UpdateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetIndicationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Limit          *uint32                `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Since          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3,oneof" json:"since,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIndicationsRequest) Reset() {
	*x = GetIndicationsRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndicationsRequest) ProtoMessage() {}

func (x *GetIndicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndicationsRequest.ProtoReflect.Descriptor instead.
func (*GetIndicationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{10}
}

func (x *GetIndicationsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GetIndicationsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetIndicationsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type GetIndicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indications   []*Indication          `protobuf:"bytes,1,rep,name=indications,proto3" json:"indications,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndicationsResponse) Reset() {
	*x = GetIndicationsResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndicationsResponse) ProtoMessage() {}

func (x *GetIndicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndicationsResponse.ProtoReflect.Descriptor instead.
func (*GetIndicationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{11}
}

func (x *GetIndicationsResponse) GetIndications() []*Indication {
	if x != nil {
		return x.Indications
	}
	return nil
}

func (x *GetIndicationsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StreamIndicationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamIndicationsRequest) Reset() {
	*x = StreamIndicationsRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndicationsRequest) ProtoMessage() {}

func (x *StreamIndicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndicationsRequest.ProtoReflect.Descriptor instead.
func (*StreamIndicationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{12}
}

func (x *StreamIndicationsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type IndicationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indication    *Indication            `protobuf:"bytes,1,opt,name=indication,proto3" json:"indication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicationMessage) Reset() {
	*x = IndicationMessage{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicationMessage) ProtoMessage() {}

func (x *IndicationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicationMessage.ProtoReflect.Descriptor instead.
func (*IndicationMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{13}
}

func (x *IndicationMessage) GetIndication() *Indication {
	if x != nil {
		return x.Indication
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{14}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *SubscriptionStats     `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsResponse) GetStats() *SubscriptionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetSubscriptionHealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubscriptionHealthRequest) Reset() {
	*x = GetSubscriptionHealthRequest{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHealthRequest) ProtoMessage() {}

func (x *GetSubscriptionHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHealthRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{16}
}

func (x *GetSubscriptionHealthRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type GetSubscriptionHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *SubscriptionHealth    `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionHealthResponse) Reset() {
	*x = GetSubscriptionHealthResponse{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionHealthResponse) ProtoMessage() {}

func (x *GetSubscriptionHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionHealthResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubscriptionHealthResponse) GetHealth() *SubscriptionHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

// Data models
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	E2NodeId      string                 `protobuf:"bytes,2,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	XappId        string                 `protobuf:"bytes,3,opt,name=xapp_id,json=xappId,proto3" json:"xapp_id,omitempty"`
	RanFunctionId uint32                 `protobuf:"varint,4,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	EventTrigger  *EventTrigger          `protobuf:"bytes,5,opt,name=event_trigger,json=eventTrigger,proto3" json:"event_trigger,omitempty"`
	Actions       []*Action              `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{18}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *Subscription) GetXappId() string {
	if x != nil {
		return x.XappId
	}
	return ""
}

func (x *Subscription) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *Subscription) GetEventTrigger() *EventTrigger {
	if x != nil {
		return x.EventTrigger
	}
	return nil
}

func (x *Subscription) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EventTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Definition    []byte                 `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	PeriodMs      *uint32                `protobuf:"varint,3,opt,name=period_ms,json=periodMs,proto3,oneof" json:"period_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTrigger) Reset() {
	*x = EventTrigger{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTrigger) ProtoMessage() {}

func (x *EventTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTrigger.ProtoReflect.Descriptor instead.
func (*EventTrigger) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{19}
}

func (x *EventTrigger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventTrigger) GetDefinition() []byte {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *EventTrigger) GetPeriodMs() uint32 {
	if x != nil && x.PeriodMs != nil {
		return *x.PeriodMs
	}
	return 0
}

type Action struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Definition       []byte                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	SubsequentAction *SubsequentAction      `protobuf:"bytes,4,opt,name=subsequent_action,json=subsequentAction,proto3,oneof" json:"subsequent_action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{20}
}

func (x *Action) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetDefinition() []byte {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Action) GetSubsequentAction() *SubsequentAction {
	if x != nil {
		return x.SubsequentAction
	}
	return nil
}

type SubsequentAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TimeToWait    uint32                 `protobuf:"varint,2,opt,name=time_to_wait,json=timeToWait,proto3" json:"time_to_wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubsequentAction) Reset() {
	*x = SubsequentAction{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubsequentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsequentAction) ProtoMessage() {}

func (x *SubsequentAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsequentAction.ProtoReflect.Descriptor instead.
func (*SubsequentAction) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{21}
}

func (x *SubsequentAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubsequentAction) GetTimeToWait() uint32 {
	if x != nil {
		return x.TimeToWait
	}
	return 0
}

type Indication struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId    string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	E2NodeId          string                 `protobuf:"bytes,2,opt,name=e2_node_id,json=e2NodeId,proto3" json:"e2_node_id,omitempty"`
	RanFunctionId     uint32                 `protobuf:"varint,3,opt,name=ran_function_id,json=ranFunctionId,proto3" json:"ran_function_id,omitempty"`
	ActionId          uint32                 `protobuf:"varint,4,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	IndicationSn      uint32                 `protobuf:"varint,5,opt,name=indication_sn,json=indicationSn,proto3" json:"indication_sn,omitempty"`
	IndicationHeader  []byte                 `protobuf:"bytes,6,opt,name=indication_header,json=indicationHeader,proto3" json:"indication_header,omitempty"`
	IndicationMessage []byte                 `protobuf:"bytes,7,opt,name=indication_message,json=indicationMessage,proto3" json:"indication_message,omitempty"`
	CallProcessId     []byte                 `protobuf:"bytes,8,opt,name=call_process_id,json=callProcessId,proto3" json:"call_process_id,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Indication) Reset() {
	*x = Indication{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indication) ProtoMessage() {}

func (x *Indication) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indication.ProtoReflect.Descriptor instead.
func (*Indication) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{22}
}

func (x *Indication) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Indication) GetE2NodeId() string {
	if x != nil {
		return x.E2NodeId
	}
	return ""
}

func (x *Indication) GetRanFunctionId() uint32 {
	if x != nil {
		return x.RanFunctionId
	}
	return 0
}

func (x *Indication) GetActionId() uint32 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *Indication) GetIndicationSn() uint32 {
	if x != nil {
		return x.IndicationSn
	}
	return 0
}

func (x *Indication) GetIndicationHeader() []byte {
	if x != nil {
		return x.IndicationHeader
	}
	return nil
}

func (x *Indication) GetIndicationMessage() []byte {
	if x != nil {
		return x.IndicationMessage
	}
	return nil
}

func (x *Indication) GetCallProcessId() []byte {
	if x != nil {
		return x.CallProcessId
	}
	return nil
}

func (x *Indication) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SubscriptionStats struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionsByStatus      map[string]uint32      `protobuf:"bytes,1,rep,name=subscriptions_by_status,json=subscriptionsByStatus,proto3" json:"subscriptions_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SubscriptionsByXapp        map[string]uint32      `protobuf:"bytes,2,rep,name=subscriptions_by_xapp,json=subscriptionsByXapp,proto3" json:"subscriptions_by_xapp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SubscriptionsByRanFunction map[string]uint32      `protobuf:"bytes,3,rep,name=subscriptions_by_ran_function,json=subscriptionsByRanFunction,proto3" json:"subscriptions_by_ran_function,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalSubscriptions         uint32                 `protobuf:"varint,4,opt,name=total_subscriptions,json=totalSubscriptions,proto3" json:"total_subscriptions,omitempty"`
	ActiveIndicationsPerSecond uint32                 `protobuf:"varint,5,opt,name=active_indications_per_second,json=activeIndicationsPerSecond,proto3" json:"active_indications_per_second,omitempty"`
	LastUpdated                *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SubscriptionStats) Reset() {
	*x = SubscriptionStats{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionStats) ProtoMessage() {}

func (x *SubscriptionStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionStats.ProtoReflect.Descriptor instead.
func (*SubscriptionStats) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{23}
}

func (x *SubscriptionStats) GetSubscriptionsByStatus() map[string]uint32 {
	if x != nil {
		return x.SubscriptionsByStatus
	}
	return nil
}

func (x *SubscriptionStats) GetSubscriptionsByXapp() map[string]uint32 {
	if x != nil {
		return x.SubscriptionsByXapp
	}
	return nil
}

func (x *SubscriptionStats) GetSubscriptionsByRanFunction() map[string]uint32 {
	if x != nil {
		return x.SubscriptionsByRanFunction
	}
	return nil
}

func (x *SubscriptionStats) GetTotalSubscriptions() uint32 {
	if x != nil {
		return x.TotalSubscriptions
	}
	return 0
}

func (x *SubscriptionStats) GetActiveIndicationsPerSecond() uint32 {
	if x != nil {
		return x.ActiveIndicationsPerSecond
	}
	return 0
}

func (x *SubscriptionStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type SubscriptionHealth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId  string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	IsHealthy       bool                   `protobuf:"varint,2,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	IndicationCount uint32                 `protobuf:"varint,3,opt,name=indication_count,json=indicationCount,proto3" json:"indication_count,omitempty"`
	LastIndication  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_indication,json=lastIndication,proto3" json:"last_indication,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscriptionHealth) Reset() {
	*x = SubscriptionHealth{}
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionHealth) ProtoMessage() {}

func (x *SubscriptionHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_submgr_submgr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionHealth.ProtoReflect.Descriptor instead.
func (*SubscriptionHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_submgr_submgr_proto_rawDescGZIP(), []int{24}
}

func (x *SubscriptionHealth) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionHealth) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *SubscriptionHealth) GetIndicationCount() uint32 {
	if x != nil {
		return x.IndicationCount
	}
	return 0
}

func (x *SubscriptionHealth) GetLastIndication() *timestamppb.Timestamp {
	if x != nil {
		return x.LastIndication
	}
	return nil
}

func (x *SubscriptionHealth) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_api_proto_submgr_submgr_proto protoreflect.FileDescriptor

const file_api_proto_submgr_submgr_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/submgr/submgr.proto\x12\x06submgr\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x1c\n" +
	"\n" +
	"e2_node_id\x18\x01 \x01(\tR\be2NodeId\x12\x17\n" +
	"\axapp_id\x18\x02 \x01(\tR\x06xappId\x12&\n" +
	"\x0fran_function_id\x18\x03 \x01(\rR\rranFunctionId\x129\n" +
	"\revent_trigger\x18\x04 \x01(\v2\x14.submgr.EventTriggerR\feventTrigger\x12(\n" +
	"\aactions\x18\x05 \x03(\v2\x0e.submgr.ActionR\aactions\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\rR\ttimeoutMs\"y\n" +
	"\x1aCreateSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xab\x02\n" +
	"\x17GetSubscriptionsRequest\x12!\n" +
	"\n" +
	"e2_node_id\x18\x01 \x01(\tH\x00R\be2NodeId\x88\x01\x01\x12\x1c\n" +
	"\axapp_id\x18\x02 \x01(\tH\x01R\x06xappId\x88\x01\x01\x12+\n" +
	"\x0fran_function_id\x18\x03 \x01(\rH\x02R\rranFunctionId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x03R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\rH\x04R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x06 \x01(\rH\x05R\x06offset\x88\x01\x01B\r\n" +
	"\v_e2_node_idB\n" +
	"\n" +
	"\b_xapp_idB\x12\n" +
	"\x10_ran_function_idB\t\n" +
	"\a_statusB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"l\n" +
	"\x18GetSubscriptionsResponse\x12:\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x14.submgr.SubscriptionR\rsubscriptions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"A\n" +
	"\x16GetSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"S\n" +
	"\x17GetSubscriptionResponse\x128\n" +
	"\fsubscription\x18\x01 \x01(\v2\x14.submgr.SubscriptionR\fsubscription\"\xa9\x01\n" +
	"\x19UpdateSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x129\n" +
	"\revent_trigger\x18\x02 \x01(\v2\x14.submgr.EventTriggerR\feventTrigger\x12(\n" +
	"\aactions\x18\x03 \x03(\v2\x0e.submgr.ActionR\aactions\"P\n" +
	"\x1aUpdateSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x19DeleteSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"P\n" +
	"\x1aDeleteSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\x15GetIndicationsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\rH\x00R\x05limit\x88\x01\x01\x125\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x05since\x88\x01\x01B\b\n" +
	"\x06_limitB\b\n" +
	"\x06_since\"d\n" +
	"\x16GetIndicationsResponse\x124\n" +
	"\vindications\x18\x01 \x03(\v2\x12.submgr.IndicationR\vindications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"C\n" +
	"\x18StreamIndicationsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"G\n" +
	"\x11IndicationMessage\x122\n" +
	"\n" +
	"indication\x18\x01 \x01(\v2\x12.submgr.IndicationR\n" +
	"indication\"\x11\n" +
	"\x0fGetStatsRequest\"C\n" +
	"\x10GetStatsResponse\x12/\n" +
	"\x05stats\x18\x01 \x01(\v2\x19.submgr.SubscriptionStatsR\x05stats\"G\n" +
	"\x1cGetSubscriptionHealthRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"S\n" +
	"\x1dGetSubscriptionHealthResponse\x122\n" +
	"\x06health\x18\x01 \x01(\v2\x1a.submgr.SubscriptionHealthR\x06health\"\x95\x03\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\n" +
	"e2_node_id\x18\x02 \x01(\tR\be2NodeId\x12\x17\n" +
	"\axapp_id\x18\x03 \x01(\tR\x06xappId\x12&\n" +
	"\x0fran_function_id\x18\x04 \x01(\rR\rranFunctionId\x129\n" +
	"\revent_trigger\x18\x05 \x01(\v2\x14.submgr.EventTriggerR\feventTrigger\x12(\n" +
	"\aactions\x18\x06 \x03(\v2\x0e.submgr.ActionR\aactions\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\fEventTrigger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\fR\n" +
	"definition\x12 \n" +
	"\tperiod_ms\x18\x03 \x01(\rH\x00R\bperiodMs\x88\x01\x01B\f\n" +
	"\n" +
	"_period_ms\"\xae\x01\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\fR\n" +
	"definition\x12J\n" +
	"\x11subsequent_action\x18\x04 \x01(\v2\x18.submgr.SubsequentActionH\x00R\x10subsequentAction\x88\x01\x01B\x14\n" +
	"\x12_subsequent_action\"H\n" +
	"\x10SubsequentAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\ftime_to_wait\x18\x02 \x01(\rR\n" +
	"timeToWait\"\xfb\x02\n" +
	"\n" +
	"Indication\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1c\n" +
	"\n" +
	"e2_node_id\x18\x02 \x01(\tR\be2NodeId\x12&\n" +
	"\x0fran_function_id\x18\x03 \x01(\rR\rranFunctionId\x12\x1b\n" +
	"\taction_id\x18\x04 \x01(\rR\bactionId\x12#\n" +
	"\rindication_sn\x18\x05 \x01(\rR\findicationSn\x12+\n" +
	"\x11indication_header\x18\x06 \x01(\fR\x10indicationHeader\x12-\n" +
	"\x12indication_message\x18\a \x01(\fR\x11indicationMessage\x12&\n" +
	"\x0fcall_process_id\x18\b \x01(\fR\rcallProcessId\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xfb\x05\n" +
	"\x11SubscriptionStats\x12l\n" +
	"\x17subscriptions_by_status\x18\x01 \x03(\v24.submgr.SubscriptionStats.SubscriptionsByStatusEntryR\x15subscriptionsByStatus\x12f\n" +
	"\x15subscriptions_by_xapp\x18\x02 \x03(\v22.submgr.SubscriptionStats.SubscriptionsByXappEntryR\x13subscriptionsByXapp\x12|\n" +
	"\x1dsubscriptions_by_ran_function\x18\x03 \x03(\v29.submgr.SubscriptionStats.SubscriptionsByRanFunctionEntryR\x1asubscriptionsByRanFunction\x12/\n" +
	"\x13total_subscriptions\x18\x04 \x01(\rR\x12totalSubscriptions\x12A\n" +
	"\x1dactive_indications_per_second\x18\x05 \x01(\rR\x1aactiveIndicationsPerSecond\x12=\n" +
	"\flast_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aH\n" +
	"\x1aSubscriptionsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aF\n" +
	"\x18SubscriptionsByXappEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aM\n" +
	"\x1fSubscriptionsByRanFunctionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x12SubscriptionHealth\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x02 \x01(\bR\tisHealthy\x12)\n" +
	"\x10indication_count\x18\x03 \x01(\rR\x0findicationCount\x12C\n" +
	"\x0flast_indication\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastIndication\x12%\n" +
	"\x0estatus_message\x18\x05 \x01(\tR\rstatusMessage2\xa1\x06\n" +
	"\x13SubscriptionManager\x12[\n" +
	"\x12CreateSubscription\x12!.submgr.CreateSubscriptionRequest\x1a\".submgr.CreateSubscriptionResponse\x12U\n" +
	"\x10GetSubscriptions\x12\x1f.submgr.GetSubscriptionsRequest\x1a .submgr.GetSubscriptionsResponse\x12R\n" +
	"\x0fGetSubscription\x12\x1e.submgr.GetSubscriptionRequest\x1a\x1f.submgr.GetSubscriptionResponse\x12[\n" +
	"\x12UpdateSubscription\x12!.submgr.UpdateSubscriptionRequest\x1a\".submgr.UpdateSubscriptionResponse\x12[\n" +
	"\x12DeleteSubscription\x12!.submgr.DeleteSubscriptionRequest\x1a\".submgr.DeleteSubscriptionResponse\x12O\n" +
	"\x0eGetIndications\x12\x1d.submgr.GetIndicationsRequest\x1a\x1e.submgr.GetIndicationsResponse\x12R\n" +
	"\x11StreamIndications\x12 .submgr.StreamIndicationsRequest\x1a\x19.submgr.IndicationMessage0\x01\x12=\n" +
	"\bGetStats\x12\x17.submgr.GetStatsRequest\x1a\x18.submgr.GetStatsResponse\x12d\n" +
	"\x15GetSubscriptionHealth\x12$.submgr.GetSubscriptionHealthRequest\x1a%.submgr.GetSubscriptionHealthResponseB2Z0github.com/oran/near-rt-ric-new/api/proto/submgrb\x06proto3"

var (
	file_api_proto_submgr_submgr_proto_rawDescOnce sync.Once
	file_api_proto_submgr_submgr_proto_rawDescData []byte
)

func file_api_proto_submgr_submgr_proto_rawDescGZIP() []byte {
	file_api_proto_submgr_submgr_proto_rawDescOnce.Do(func() {
		file_api_proto_submgr_submgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_submgr_submgr_proto_rawDesc), len(file_api_proto_submgr_submgr_proto_rawDesc)))
	})
	return file_api_proto_submgr_submgr_proto_rawDescData
}

var file_api_proto_submgr_submgr_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_proto_submgr_submgr_proto_goTypes = []any{
	(*CreateSubscriptionRequest)(nil),     // 0: submgr.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),    // 1: submgr.CreateSubscriptionResponse
	(*GetSubscriptionsRequest)(nil),       // 2: submgr.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),      // 3: submgr.GetSubscriptionsResponse
	(*GetSubscriptionRequest)(nil),        // 4: submgr.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),       // 5: submgr.GetSubscriptionResponse
	(*UpdateSubscriptionRequest)(nil),     // 6: submgr.UpdateSubscriptionRequest
	(*UpdateSubscriptionResponse)(nil),    // 7: submgr.UpdateSubscriptionResponse
	(*DeleteSubscriptionRequest)(nil),     // 8: submgr.DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil),    // 9: submgr.DeleteSubscriptionResponse
	(*GetIndicationsRequest)(nil),         // 10: submgr.GetIndicationsRequest
	(*GetIndicationsResponse)(nil),        // 11: submgr.GetIndicationsResponse
	(*StreamIndicationsRequest)(nil),      // 12: submgr.StreamIndicationsRequest
	(*IndicationMessage)(nil),             // 13: submgr.IndicationMessage
	(*GetStatsRequest)(nil),               // 14: submgr.GetStatsRequest
	(*GetStatsResponse)(nil),              // 15: submgr.GetStatsResponse
	(*GetSubscriptionHealthRequest)(nil),  // 16: submgr.GetSubscriptionHealthRequest
	(*GetSubscriptionHealthResponse)(nil), // 17: submgr.GetSubscriptionHealthResponse
	(*Subscription)(nil),                  // 18: submgr.Subscription
	(*EventTrigger)(nil),                  // 19: submgr.EventTrigger
	(*Action)(nil),                        // 20: submgr.Action
	(*SubsequentAction)(nil),              // 21: submgr.SubsequentAction
	(*Indication)(nil),                    // 22: submgr.Indication
	(*SubscriptionStats)(nil),             // 23: submgr.SubscriptionStats
	(*SubscriptionHealth)(nil),            // 24: submgr.SubscriptionHealth
	nil,                                   // 25: submgr.SubscriptionStats.SubscriptionsByStatusEntry
	nil,                                   // 26: submgr.SubscriptionStats.SubscriptionsByXappEntry
	nil,                                   // 27: submgr.SubscriptionStats.SubscriptionsByRanFunctionEntry
	(*timestamppb.Timestamp)(nil),         // 28: google.protobuf.Timestamp
}
var file_api_proto_submgr_submgr_proto_depIdxs = []int32{
	19, // 0: submgr.CreateSubscriptionRequest.event_trigger:type_name -> submgr.EventTrigger
	20, // 1: submgr.CreateSubscriptionRequest.actions:type_name -> submgr.Action
	18, // 2: submgr.GetSubscriptionsResponse.subscriptions:type_name -> submgr.Subscription
	18, // 3: submgr.GetSubscriptionResponse.subscription:type_name -> submgr.Subscription
	19, // 4: submgr.UpdateSubscriptionRequest.event_trigger:type_name -> submgr.EventTrigger
	20, // 5: submgr.UpdateSubscriptionRequest.actions:type_name -> submgr.Action
	28, // 6: submgr.GetIndicationsRequest.since:type_name -> google.protobuf.Timestamp
	22, // 7: submgr.GetIndicationsResponse.indications:type_name -> submgr.Indication
	22, // 8: submgr.IndicationMessage.indication:type_name -> submgr.Indication
	23, // 9: submgr.GetStatsResponse.stats:type_name -> submgr.SubscriptionStats
	24, // 10: submgr.GetSubscriptionHealthResponse.health:type_name -> submgr.SubscriptionHealth
	19, // 11: submgr.Subscription.event_trigger:type_name -> submgr.EventTrigger
	20, // 12: submgr.Subscription.actions:type_name -> submgr.Action
	28, // 13: submgr.Subscription.created_at:type_name -> google.protobuf.Timestamp
	28, // 14: submgr.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	21, // 15: submgr.Action.subsequent_action:type_name -> submgr.SubsequentAction
	28, // 16: submgr.Indication.timestamp:type_name -> google.protobuf.Timestamp
	25, // 17: submgr.SubscriptionStats.subscriptions_by_status:type_name -> submgr.SubscriptionStats.SubscriptionsByStatusEntry
	26, // 18: submgr.SubscriptionStats.subscriptions_by_xapp:type_name -> submgr.SubscriptionStats.SubscriptionsByXappEntry
	27, // 19: submgr.SubscriptionStats.subscriptions_by_ran_function:type_name -> submgr.SubscriptionStats.SubscriptionsByRanFunctionEntry
	28, // 20: submgr.SubscriptionStats.last_updated:type_name -> google.protobuf.Timestamp
	28, // 21: submgr.SubscriptionHealth.last_indication:type_name -> google.protobuf.Timestamp
	0,  // 22: submgr.SubscriptionManager.CreateSubscription:input_type -> submgr.CreateSubscriptionRequest
	2,  // 23: submgr.SubscriptionManager.GetSubscriptions:input_type -> submgr.GetSubscriptionsRequest
	4,  // 24: submgr.SubscriptionManager.GetSubscription:input_type -> submgr.GetSubscriptionRequest
	6,  // 25: submgr.SubscriptionManager.UpdateSubscription:input_type -> submgr.UpdateSubscriptionRequest
	8,  // 26: submgr.SubscriptionManager.DeleteSubscription:input_type -> submgr.DeleteSubscriptionRequest
	10, // 27: submgr.SubscriptionManager.GetIndications:input_type -> submgr.GetIndicationsRequest
	12, // 28: submgr.SubscriptionManager.StreamIndications:input_type -> submgr.StreamIndicationsRequest
	14, // 29: submgr.SubscriptionManager.GetStats:input_type -> submgr.GetStatsRequest
	16, // 30: submgr.SubscriptionManager.GetSubscriptionHealth:input_type -> submgr.GetSubscriptionHealthRequest
	1,  // 31: submgr.SubscriptionManager.CreateSubscription:output_type -> submgr.CreateSubscriptionResponse
	3,  // 32: submgr.SubscriptionManager.GetSubscriptions:output_type -> submgr.GetSubscriptionsResponse
	5,  // 33: submgr.SubscriptionManager.GetSubscription:output_type -> submgr.GetSubscriptionResponse
	7,  // 34: submgr.SubscriptionManager.UpdateSubscription:output_type -> submgr.UpdateSubscriptionResponse
	9,  // 35: submgr.SubscriptionManager.DeleteSubscription:output_type -> submgr.DeleteSubscriptionResponse
	11, // 36: submgr.SubscriptionManager.GetIndications:output_type -> submgr.GetIndicationsResponse
	13, // 37: submgr.SubscriptionManager.StreamIndications:output_type -> submgr.IndicationMessage
	15, // 38: submgr.SubscriptionManager.GetStats:output_type -> submgr.GetStatsResponse
	17, // 39: submgr.SubscriptionManager.GetSubscriptionHealth:output_type -> submgr.GetSubscriptionHealthResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_submgr_submgr_proto_init() }
func file_api_proto_submgr_submgr_proto_init() {
	if File_api_proto_submgr_submgr_proto != nil {
		return
	}
	file_api_proto_submgr_submgr_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_submgr_submgr_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_submgr_submgr_proto_msgTypes[19].OneofWrappers = []any{}
	file_api_proto_submgr_submgr_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_submgr_submgr_proto_rawDesc), len(file_api_proto_submgr_submgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_submgr_submgr_proto_goTypes,
		DependencyIndexes: file_api_proto_submgr_submgr_proto_depIdxs,
		MessageInfos:      file_api_proto_submgr_submgr_proto_msgTypes,
	}.Build()
	File_api_proto_submgr_submgr_proto = out.File
	file_api_proto_submgr_submgr_proto_goTypes = nil
	file_api_proto_submgr_submgr_proto_depIdxs = nil
}
