// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: api/proto/rtmgr/rtmgr.proto

package rtmgr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutingManager_CreateRoute_FullMethodName        = "/rtmgr.RoutingManager/CreateRoute"
	RoutingManager_GetRoutes_FullMethodName          = "/rtmgr.RoutingManager/GetRoutes"
	RoutingManager_GetRoute_FullMethodName           = "/rtmgr.RoutingManager/GetRoute"
	RoutingManager_UpdateRoute_FullMethodName        = "/rtmgr.RoutingManager/UpdateRoute"
	RoutingManager_DeleteRoute_FullMethodName        = "/rtmgr.RoutingManager/DeleteRoute"
	RoutingManager_GetRoutingTable_FullMethodName    = "/rtmgr.RoutingManager/GetRoutingTable"
	RoutingManager_UpdateRoutingTable_FullMethodName = "/rtmgr.RoutingManager/UpdateRoutingTable"
	RoutingManager_RegisterXApp_FullMethodName       = "/rtmgr.RoutingManager/RegisterXApp"
	RoutingManager_UnregisterXApp_FullMethodName     = "/rtmgr.RoutingManager/UnregisterXApp"
	RoutingManager_GetXApps_FullMethodName           = "/rtmgr.RoutingManager/GetXApps"
	RoutingManager_GetStats_FullMethodName           = "/rtmgr.RoutingManager/GetStats"
	RoutingManager_GetHealth_FullMethodName          = "/rtmgr.RoutingManager/GetHealth"
)

// RoutingManagerClient is the client API for RoutingManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Routing Manager service definition
type RoutingManagerClient interface {
	// Route management operations
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error)
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
	UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	// Routing table operations
	GetRoutingTable(ctx context.Context, in *GetRoutingTableRequest, opts ...grpc.CallOption) (*GetRoutingTableResponse, error)
	UpdateRoutingTable(ctx context.Context, in *UpdateRoutingTableRequest, opts ...grpc.CallOption) (*UpdateRoutingTableResponse, error)
	// xApp registration and discovery
	RegisterXApp(ctx context.Context, in *RegisterXAppRequest, opts ...grpc.CallOption) (*RegisterXAppResponse, error)
	UnregisterXApp(ctx context.Context, in *UnregisterXAppRequest, opts ...grpc.CallOption) (*UnregisterXAppResponse, error)
	GetXApps(ctx context.Context, in *GetXAppsRequest, opts ...grpc.CallOption) (*GetXAppsResponse, error)
	// Health and statistics
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
}

type routingManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingManagerClient(cc grpc.ClientConnInterface) RoutingManagerClient {
	return &routingManagerClient{cc}
}

func (c *routingManagerClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRouteResponse)
	err := c.cc.Invoke(ctx, RoutingManager_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, RoutingManager_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, RoutingManager_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRouteResponse)
	err := c.cc.Invoke(ctx, RoutingManager_UpdateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, RoutingManager_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetRoutingTable(ctx context.Context, in *GetRoutingTableRequest, opts ...grpc.CallOption) (*GetRoutingTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingTableResponse)
	err := c.cc.Invoke(ctx, RoutingManager_GetRoutingTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) UpdateRoutingTable(ctx context.Context, in *UpdateRoutingTableRequest, opts ...grpc.CallOption) (*UpdateRoutingTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoutingTableResponse)
	err := c.cc.Invoke(ctx, RoutingManager_UpdateRoutingTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) RegisterXApp(ctx context.Context, in *RegisterXAppRequest, opts ...grpc.CallOption) (*RegisterXAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterXAppResponse)
	err := c.cc.Invoke(ctx, RoutingManager_RegisterXApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) UnregisterXApp(ctx context.Context, in *UnregisterXAppRequest, opts ...grpc.CallOption) (*UnregisterXAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterXAppResponse)
	err := c.cc.Invoke(ctx, RoutingManager_UnregisterXApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetXApps(ctx context.Context, in *GetXAppsRequest, opts ...grpc.CallOption) (*GetXAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetXAppsResponse)
	err := c.cc.Invoke(ctx, RoutingManager_GetXApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, RoutingManager_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, RoutingManager_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingManagerServer is the server API for RoutingManager service.
// All implementations must embed UnimplementedRoutingManagerServer
// for forward compatibility.
//
// Routing Manager service definition
type RoutingManagerServer interface {
	// Route management operations
	CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error)
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	// Routing table operations
	GetRoutingTable(context.Context, *GetRoutingTableRequest) (*GetRoutingTableResponse, error)
	UpdateRoutingTable(context.Context, *UpdateRoutingTableRequest) (*UpdateRoutingTableResponse, error)
	// xApp registration and discovery
	RegisterXApp(context.Context, *RegisterXAppRequest) (*RegisterXAppResponse, error)
	UnregisterXApp(context.Context, *UnregisterXAppRequest) (*UnregisterXAppResponse, error)
	GetXApps(context.Context, *GetXAppsRequest) (*GetXAppsResponse, error)
	// Health and statistics
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	mustEmbedUnimplementedRoutingManagerServer()
}

// UnimplementedRoutingManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingManagerServer struct{}

func (UnimplementedRoutingManagerServer) CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedRoutingManagerServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedRoutingManagerServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedRoutingManagerServer) UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoute not implemented")
}
func (UnimplementedRoutingManagerServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedRoutingManagerServer) GetRoutingTable(context.Context, *GetRoutingTableRequest) (*GetRoutingTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingTable not implemented")
}
func (UnimplementedRoutingManagerServer) UpdateRoutingTable(context.Context, *UpdateRoutingTableRequest) (*UpdateRoutingTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoutingTable not implemented")
}
func (UnimplementedRoutingManagerServer) RegisterXApp(context.Context, *RegisterXAppRequest) (*RegisterXAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterXApp not implemented")
}
func (UnimplementedRoutingManagerServer) UnregisterXApp(context.Context, *UnregisterXAppRequest) (*UnregisterXAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterXApp not implemented")
}
func (UnimplementedRoutingManagerServer) GetXApps(context.Context, *GetXAppsRequest) (*GetXAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetXApps not implemented")
}
func (UnimplementedRoutingManagerServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedRoutingManagerServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedRoutingManagerServer) mustEmbedUnimplementedRoutingManagerServer() {}
func (UnimplementedRoutingManagerServer) testEmbeddedByValue()                        {}

// UnsafeRoutingManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingManagerServer will
// result in compilation errors.
type UnsafeRoutingManagerServer interface {
	mustEmbedUnimplementedRoutingManagerServer()
}

func RegisterRoutingManagerServer(s grpc.ServiceRegistrar, srv RoutingManagerServer) {
	// If the following call pancis, it indicates UnimplementedRoutingManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingManager_ServiceDesc, srv)
}

func _RoutingManager_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).CreateRoute(ctx, req.(*CreateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_UpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).UpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_UpdateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).UpdateRoute(ctx, req.(*UpdateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_GetRoutingTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).GetRoutingTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_GetRoutingTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).GetRoutingTable(ctx, req.(*GetRoutingTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_UpdateRoutingTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoutingTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).UpdateRoutingTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_UpdateRoutingTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).UpdateRoutingTable(ctx, req.(*UpdateRoutingTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_RegisterXApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterXAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).RegisterXApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_RegisterXApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).RegisterXApp(ctx, req.(*RegisterXAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_UnregisterXApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterXAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).UnregisterXApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_UnregisterXApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).UnregisterXApp(ctx, req.(*UnregisterXAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_GetXApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetXAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).GetXApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_GetXApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).GetXApps(ctx, req.(*GetXAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingManager_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingManagerServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingManager_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingManagerServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingManager_ServiceDesc is the grpc.ServiceDesc for RoutingManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtmgr.RoutingManager",
	HandlerType: (*RoutingManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoute",
			Handler:    _RoutingManager_CreateRoute_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _RoutingManager_GetRoutes_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _RoutingManager_GetRoute_Handler,
		},
		{
			MethodName: "UpdateRoute",
			Handler:    _RoutingManager_UpdateRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _RoutingManager_DeleteRoute_Handler,
		},
		{
			MethodName: "GetRoutingTable",
			Handler:    _RoutingManager_GetRoutingTable_Handler,
		},
		{
			MethodName: "UpdateRoutingTable",
			Handler:    _RoutingManager_UpdateRoutingTable_Handler,
		},
		{
			MethodName: "RegisterXApp",
			Handler:    _RoutingManager_RegisterXApp_Handler,
		},
		{
			MethodName: "UnregisterXApp",
			Handler:    _RoutingManager_UnregisterXApp_Handler,
		},
		{
			MethodName: "GetXApps",
			Handler:    _RoutingManager_GetXApps_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _RoutingManager_GetStats_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _RoutingManager_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/rtmgr/rtmgr.proto",
}
