// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.1
// source: api/proto/rtmgr/rtmgr.proto

package rtmgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages for route operations
type CreateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type CreateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteResponse) Reset() {
	*x = CreateRouteResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteResponse) ProtoMessage() {}

func (x *CreateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteResponse.ProtoReflect.Descriptor instead.
func (*CreateRouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRouteResponse) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CreateRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRouteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceXapp    *string                `protobuf:"bytes,1,opt,name=source_xapp,json=sourceXapp,proto3,oneof" json:"source_xapp,omitempty"`
	TargetXapp    *string                `protobuf:"bytes,2,opt,name=target_xapp,json=targetXapp,proto3,oneof" json:"target_xapp,omitempty"`
	MessageType   *uint32                `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3,oneof" json:"message_type,omitempty"`
	Limit         *uint32                `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint32                `protobuf:"varint,5,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesRequest) Reset() {
	*x = GetRoutesRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesRequest) ProtoMessage() {}

func (x *GetRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetRoutesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoutesRequest) GetSourceXapp() string {
	if x != nil && x.SourceXapp != nil {
		return *x.SourceXapp
	}
	return ""
}

func (x *GetRoutesRequest) GetTargetXapp() string {
	if x != nil && x.TargetXapp != nil {
		return *x.TargetXapp
	}
	return ""
}

func (x *GetRoutesRequest) GetMessageType() uint32 {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return 0
}

func (x *GetRoutesRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetRoutesRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesResponse) Reset() {
	*x = GetRoutesResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesResponse) ProtoMessage() {}

func (x *GetRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetRoutesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetRoutesResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{4}
}

func (x *GetRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type GetRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{5}
}

func (x *GetRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type UpdateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Route         *Route                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteRequest) Reset() {
	*x = UpdateRouteRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteRequest) ProtoMessage() {}

func (x *UpdateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *UpdateRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type UpdateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteResponse) Reset() {
	*x = UpdateRouteResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteResponse) ProtoMessage() {}

func (x *UpdateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteResponse.ProtoReflect.Descriptor instead.
func (*UpdateRouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRouteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type DeleteRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteResponse) Reset() {
	*x = DeleteRouteResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteResponse) ProtoMessage() {}

func (x *DeleteRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRouteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Routing table operations
type GetRoutingTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutingTableRequest) Reset() {
	*x = GetRoutingTableRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutingTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutingTableRequest) ProtoMessage() {}

func (x *GetRoutingTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutingTableRequest.ProtoReflect.Descriptor instead.
func (*GetRoutingTableRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{10}
}

type GetRoutingTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingTable  *RoutingTable          `protobuf:"bytes,1,opt,name=routing_table,json=routingTable,proto3" json:"routing_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutingTableResponse) Reset() {
	*x = GetRoutingTableResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutingTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutingTableResponse) ProtoMessage() {}

func (x *GetRoutingTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutingTableResponse.ProtoReflect.Descriptor instead.
func (*GetRoutingTableResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoutingTableResponse) GetRoutingTable() *RoutingTable {
	if x != nil {
		return x.RoutingTable
	}
	return nil
}

type UpdateRoutingTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingTable  *RoutingTable          `protobuf:"bytes,1,opt,name=routing_table,json=routingTable,proto3" json:"routing_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutingTableRequest) Reset() {
	*x = UpdateRoutingTableRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutingTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutingTableRequest) ProtoMessage() {}

func (x *UpdateRoutingTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutingTableRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoutingTableRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRoutingTableRequest) GetRoutingTable() *RoutingTable {
	if x != nil {
		return x.RoutingTable
	}
	return nil
}

type UpdateRoutingTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutingTableResponse) Reset() {
	*x = UpdateRoutingTableResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutingTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutingTableResponse) ProtoMessage() {}

func (x *UpdateRoutingTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutingTableResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoutingTableResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRoutingTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRoutingTableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// xApp registration operations
type RegisterXAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XappInfo      *XAppInfo              `protobuf:"bytes,1,opt,name=xapp_info,json=xappInfo,proto3" json:"xapp_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterXAppRequest) Reset() {
	*x = RegisterXAppRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterXAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterXAppRequest) ProtoMessage() {}

func (x *RegisterXAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterXAppRequest.ProtoReflect.Descriptor instead.
func (*RegisterXAppRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterXAppRequest) GetXappInfo() *XAppInfo {
	if x != nil {
		return x.XappInfo
	}
	return nil
}

type RegisterXAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterXAppResponse) Reset() {
	*x = RegisterXAppResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterXAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterXAppResponse) ProtoMessage() {}

func (x *RegisterXAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterXAppResponse.ProtoReflect.Descriptor instead.
func (*RegisterXAppResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterXAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterXAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnregisterXAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XappName      string                 `protobuf:"bytes,1,opt,name=xapp_name,json=xappName,proto3" json:"xapp_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterXAppRequest) Reset() {
	*x = UnregisterXAppRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterXAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterXAppRequest) ProtoMessage() {}

func (x *UnregisterXAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterXAppRequest.ProtoReflect.Descriptor instead.
func (*UnregisterXAppRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{16}
}

func (x *UnregisterXAppRequest) GetXappName() string {
	if x != nil {
		return x.XappName
	}
	return ""
}

type UnregisterXAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterXAppResponse) Reset() {
	*x = UnregisterXAppResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterXAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterXAppResponse) ProtoMessage() {}

func (x *UnregisterXAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterXAppResponse.ProtoReflect.Descriptor instead.
func (*UnregisterXAppResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{17}
}

func (x *UnregisterXAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterXAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetXAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *string                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXAppsRequest) Reset() {
	*x = GetXAppsRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXAppsRequest) ProtoMessage() {}

func (x *GetXAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXAppsRequest.ProtoReflect.Descriptor instead.
func (*GetXAppsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{18}
}

func (x *GetXAppsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetXAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xapps         []*XAppInfo            `protobuf:"bytes,1,rep,name=xapps,proto3" json:"xapps,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXAppsResponse) Reset() {
	*x = GetXAppsResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXAppsResponse) ProtoMessage() {}

func (x *GetXAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXAppsResponse.ProtoReflect.Descriptor instead.
func (*GetXAppsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{19}
}

func (x *GetXAppsResponse) GetXapps() []*XAppInfo {
	if x != nil {
		return x.Xapps
	}
	return nil
}

func (x *GetXAppsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Health and statistics
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{20}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *RoutingStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatsResponse) GetStats() *RoutingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{22}
}

type GetHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *RoutingHealth         `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{23}
}

func (x *GetHealthResponse) GetHealth() *RoutingHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

// Data models
type Route struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceXapp     string                 `protobuf:"bytes,2,opt,name=source_xapp,json=sourceXapp,proto3" json:"source_xapp,omitempty"`
	TargetXapp     string                 `protobuf:"bytes,3,opt,name=target_xapp,json=targetXapp,proto3" json:"target_xapp,omitempty"`
	MessageType    uint32                 `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,5,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Policy         *RoutePolicy           `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{24}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetSourceXapp() string {
	if x != nil {
		return x.SourceXapp
	}
	return ""
}

func (x *Route) GetTargetXapp() string {
	if x != nil {
		return x.TargetXapp
	}
	return ""
}

func (x *Route) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *Route) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Route) GetPolicy() *RoutePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Route) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Route) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoutePolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "round_robin", "priority", "load_balanced"
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePolicy) Reset() {
	*x = RoutePolicy{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicy) ProtoMessage() {}

func (x *RoutePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicy.ProtoReflect.Descriptor instead.
func (*RoutePolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{25}
}

func (x *RoutePolicy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RoutePolicy) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type RoutingTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RouteEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTable) Reset() {
	*x = RoutingTable{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTable) ProtoMessage() {}

func (x *RoutingTable) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTable.ProtoReflect.Descriptor instead.
func (*RoutingTable) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{26}
}

func (x *RoutingTable) GetEntries() []*RouteEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RoutingTable) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoutingTable) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type RouteEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageType     uint32                 `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	SourceEndpoint  string                 `protobuf:"bytes,2,opt,name=source_endpoint,json=sourceEndpoint,proto3" json:"source_endpoint,omitempty"`
	TargetEndpoints []string               `protobuf:"bytes,3,rep,name=target_endpoints,json=targetEndpoints,proto3" json:"target_endpoints,omitempty"`
	Policy          *RoutePolicy           `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{27}
}

func (x *RouteEntry) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *RouteEntry) GetSourceEndpoint() string {
	if x != nil {
		return x.SourceEndpoint
	}
	return ""
}

func (x *RouteEntry) GetTargetEndpoints() []string {
	if x != nil {
		return x.TargetEndpoints
	}
	return nil
}

func (x *RouteEntry) GetPolicy() *RoutePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type XAppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Endpoints     []string               `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Config        map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XAppInfo) Reset() {
	*x = XAppInfo{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAppInfo) ProtoMessage() {}

func (x *XAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAppInfo.ProtoReflect.Descriptor instead.
func (*XAppInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{28}
}

func (x *XAppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *XAppInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *XAppInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *XAppInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *XAppInfo) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *XAppInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *XAppInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *XAppInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type RoutingStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRoutes         uint32                 `protobuf:"varint,1,opt,name=total_routes,json=totalRoutes,proto3" json:"total_routes,omitempty"`
	ActiveXapps         uint32                 `protobuf:"varint,2,opt,name=active_xapps,json=activeXapps,proto3" json:"active_xapps,omitempty"`
	RoutesByMessageType map[string]uint32      `protobuf:"bytes,3,rep,name=routes_by_message_type,json=routesByMessageType,proto3" json:"routes_by_message_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XappsByStatus       map[string]uint32      `protobuf:"bytes,4,rep,name=xapps_by_status,json=xappsByStatus,proto3" json:"xapps_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MessagesRouted      uint64                 `protobuf:"varint,5,opt,name=messages_routed,json=messagesRouted,proto3" json:"messages_routed,omitempty"`
	RoutingErrors       uint64                 `protobuf:"varint,6,opt,name=routing_errors,json=routingErrors,proto3" json:"routing_errors,omitempty"`
	LastUpdated         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoutingStats) Reset() {
	*x = RoutingStats{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingStats) ProtoMessage() {}

func (x *RoutingStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingStats.ProtoReflect.Descriptor instead.
func (*RoutingStats) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{29}
}

func (x *RoutingStats) GetTotalRoutes() uint32 {
	if x != nil {
		return x.TotalRoutes
	}
	return 0
}

func (x *RoutingStats) GetActiveXapps() uint32 {
	if x != nil {
		return x.ActiveXapps
	}
	return 0
}

func (x *RoutingStats) GetRoutesByMessageType() map[string]uint32 {
	if x != nil {
		return x.RoutesByMessageType
	}
	return nil
}

func (x *RoutingStats) GetXappsByStatus() map[string]uint32 {
	if x != nil {
		return x.XappsByStatus
	}
	return nil
}

func (x *RoutingStats) GetMessagesRouted() uint64 {
	if x != nil {
		return x.MessagesRouted
	}
	return 0
}

func (x *RoutingStats) GetRoutingErrors() uint64 {
	if x != nil {
		return x.RoutingErrors
	}
	return 0
}

func (x *RoutingStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type RoutingHealth struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy         bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	StatusMessage     string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ActiveConnections uint32                 `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	FailedRoutes      uint32                 `protobuf:"varint,4,opt,name=failed_routes,json=failedRoutes,proto3" json:"failed_routes,omitempty"`
	LastHealthCheck   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_health_check,json=lastHealthCheck,proto3" json:"last_health_check,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoutingHealth) Reset() {
	*x = RoutingHealth{}
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingHealth) ProtoMessage() {}

func (x *RoutingHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingHealth.ProtoReflect.Descriptor instead.
func (*RoutingHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{30}
}

func (x *RoutingHealth) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *RoutingHealth) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *RoutingHealth) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *RoutingHealth) GetFailedRoutes() uint32 {
	if x != nil {
		return x.FailedRoutes
	}
	return 0
}

func (x *RoutingHealth) GetLastHealthCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHealthCheck
	}
	return nil
}

var File_api_proto_rtmgr_rtmgr_proto protoreflect.FileDescriptor

const file_api_proto_rtmgr_rtmgr_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/rtmgr/rtmgr.proto\x12\x05rtmgr\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x12CreateRouteRequest\x12\"\n" +
	"\x05route\x18\x01 \x01(\v2\f.rtmgr.RouteR\x05route\"d\n" +
	"\x13CreateRouteResponse\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x84\x02\n" +
	"\x10GetRoutesRequest\x12$\n" +
	"\vsource_xapp\x18\x01 \x01(\tH\x00R\n" +
	"sourceXapp\x88\x01\x01\x12$\n" +
	"\vtarget_xapp\x18\x02 \x01(\tH\x01R\n" +
	"targetXapp\x88\x01\x01\x12&\n" +
	"\fmessage_type\x18\x03 \x01(\rH\x02R\vmessageType\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x03R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x05 \x01(\rH\x04R\x06offset\x88\x01\x01B\x0e\n" +
	"\f_source_xappB\x0e\n" +
	"\f_target_xappB\x0f\n" +
	"\r_message_typeB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"O\n" +
	"\x11GetRoutesResponse\x12$\n" +
	"\x06routes\x18\x01 \x03(\v2\f.rtmgr.RouteR\x06routes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\",\n" +
	"\x0fGetRouteRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\"6\n" +
	"\x10GetRouteResponse\x12\"\n" +
	"\x05route\x18\x01 \x01(\v2\f.rtmgr.RouteR\x05route\"S\n" +
	"\x12UpdateRouteRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\"\n" +
	"\x05route\x18\x02 \x01(\v2\f.rtmgr.RouteR\x05route\"I\n" +
	"\x13UpdateRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x12DeleteRouteRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\"I\n" +
	"\x13DeleteRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x18\n" +
	"\x16GetRoutingTableRequest\"S\n" +
	"\x17GetRoutingTableResponse\x128\n" +
	"\rrouting_table\x18\x01 \x01(\v2\x13.rtmgr.RoutingTableR\froutingTable\"U\n" +
	"\x19UpdateRoutingTableRequest\x128\n" +
	"\rrouting_table\x18\x01 \x01(\v2\x13.rtmgr.RoutingTableR\froutingTable\"P\n" +
	"\x1aUpdateRoutingTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x13RegisterXAppRequest\x12,\n" +
	"\txapp_info\x18\x01 \x01(\v2\x0f.rtmgr.XAppInfoR\bxappInfo\"J\n" +
	"\x14RegisterXAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x15UnregisterXAppRequest\x12\x1b\n" +
	"\txapp_name\x18\x01 \x01(\tR\bxappName\"L\n" +
	"\x16UnregisterXAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x0fGetXAppsRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"O\n" +
	"\x10GetXAppsResponse\x12%\n" +
	"\x05xapps\x18\x01 \x03(\v2\x0f.rtmgr.XAppInfoR\x05xapps\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\x11\n" +
	"\x0fGetStatsRequest\"=\n" +
	"\x10GetStatsResponse\x12)\n" +
	"\x05stats\x18\x01 \x01(\v2\x13.rtmgr.RoutingStatsR\x05stats\"\x12\n" +
	"\x10GetHealthRequest\"A\n" +
	"\x11GetHealthResponse\x12,\n" +
	"\x06health\x18\x01 \x01(\v2\x14.rtmgr.RoutingHealthR\x06health\"\xc7\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsource_xapp\x18\x02 \x01(\tR\n" +
	"sourceXapp\x12\x1f\n" +
	"\vtarget_xapp\x18\x03 \x01(\tR\n" +
	"targetXapp\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\rR\vmessageType\x12'\n" +
	"\x0fsubscription_id\x18\x05 \x01(\tR\x0esubscriptionId\x12*\n" +
	"\x06policy\x18\x06 \x01(\v2\x12.rtmgr.RoutePolicyR\x06policy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa4\x01\n" +
	"\vRoutePolicy\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12B\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\".rtmgr.RoutePolicy.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\fRoutingTable\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.rtmgr.RouteEntryR\aentries\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xaf\x01\n" +
	"\n" +
	"RouteEntry\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\rR\vmessageType\x12'\n" +
	"\x0fsource_endpoint\x18\x02 \x01(\tR\x0esourceEndpoint\x12)\n" +
	"\x10target_endpoints\x18\x03 \x03(\tR\x0ftargetEndpoints\x12*\n" +
	"\x06policy\x18\x04 \x01(\v2\x12.rtmgr.RoutePolicyR\x06policy\"\x80\x03\n" +
	"\bXAppInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tendpoints\x18\x04 \x03(\tR\tendpoints\x123\n" +
	"\x06config\x18\x05 \x03(\v2\x1b.rtmgr.XAppInfo.ConfigEntryR\x06config\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12?\n" +
	"\rregistered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12A\n" +
	"\x0elast_heartbeat\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x04\n" +
	"\fRoutingStats\x12!\n" +
	"\ftotal_routes\x18\x01 \x01(\rR\vtotalRoutes\x12!\n" +
	"\factive_xapps\x18\x02 \x01(\rR\vactiveXapps\x12a\n" +
	"\x16routes_by_message_type\x18\x03 \x03(\v2,.rtmgr.RoutingStats.RoutesByMessageTypeEntryR\x13routesByMessageType\x12N\n" +
	"\x0fxapps_by_status\x18\x04 \x03(\v2&.rtmgr.RoutingStats.XappsByStatusEntryR\rxappsByStatus\x12'\n" +
	"\x0fmessages_routed\x18\x05 \x01(\x04R\x0emessagesRouted\x12%\n" +
	"\x0erouting_errors\x18\x06 \x01(\x04R\rroutingErrors\x12=\n" +
	"\flast_updated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aF\n" +
	"\x18RoutesByMessageTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a@\n" +
	"\x12XappsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xf1\x01\n" +
	"\rRoutingHealth\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\rR\x11activeConnections\x12#\n" +
	"\rfailed_routes\x18\x04 \x01(\rR\ffailedRoutes\x12F\n" +
	"\x11last_health_check\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHealthCheck2\xde\x06\n" +
	"\x0eRoutingManager\x12D\n" +
	"\vCreateRoute\x12\x19.rtmgr.CreateRouteRequest\x1a\x1a.rtmgr.CreateRouteResponse\x12>\n" +
	"\tGetRoutes\x12\x17.rtmgr.GetRoutesRequest\x1a\x18.rtmgr.GetRoutesResponse\x12;\n" +
	"\bGetRoute\x12\x16.rtmgr.GetRouteRequest\x1a\x17.rtmgr.GetRouteResponse\x12D\n" +
	"\vUpdateRoute\x12\x19.rtmgr.UpdateRouteRequest\x1a\x1a.rtmgr.UpdateRouteResponse\x12D\n" +
	"\vDeleteRoute\x12\x19.rtmgr.DeleteRouteRequest\x1a\x1a.rtmgr.DeleteRouteResponse\x12P\n" +
	"\x0fGetRoutingTable\x12\x1d.rtmgr.GetRoutingTableRequest\x1a\x1e.rtmgr.GetRoutingTableResponse\x12Y\n" +
	"\x12UpdateRoutingTable\x12 .rtmgr.UpdateRoutingTableRequest\x1a!.rtmgr.UpdateRoutingTableResponse\x12G\n" +
	"\fRegisterXApp\x12\x1a.rtmgr.RegisterXAppRequest\x1a\x1b.rtmgr.RegisterXAppResponse\x12M\n" +
	"\x0eUnregisterXApp\x12\x1c.rtmgr.UnregisterXAppRequest\x1a\x1d.rtmgr.UnregisterXAppResponse\x12;\n" +
	"\bGetXApps\x12\x16.rtmgr.GetXAppsRequest\x1a\x17.rtmgr.GetXAppsResponse\x12;\n" +
	"\bGetStats\x12\x16.rtmgr.GetStatsRequest\x1a\x17.rtmgr.GetStatsResponse\x12>\n" +
	"\tGetHealth\x12\x17.rtmgr.GetHealthRequest\x1a\x18.rtmgr.GetHealthResponseB1Z/github.com/oran/near-rt-ric-new/api/proto/rtmgrb\x06proto3"

var (
	file_api_proto_rtmgr_rtmgr_proto_rawDescOnce sync.Once
	file_api_proto_rtmgr_rtmgr_proto_rawDescData []byte
)

func file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP() []byte {
	file_api_proto_rtmgr_rtmgr_proto_rawDescOnce.Do(func() {
		file_api_proto_rtmgr_rtmgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rtmgr_rtmgr_proto_rawDesc), len(file_api_proto_rtmgr_rtmgr_proto_rawDesc)))
	})
	return file_api_proto_rtmgr_rtmgr_proto_rawDescData
}

var file_api_proto_rtmgr_rtmgr_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_proto_rtmgr_rtmgr_proto_goTypes = []any{
	(*CreateRouteRequest)(nil),         // 0: rtmgr.CreateRouteRequest
	(*CreateRouteResponse)(nil),        // 1: rtmgr.CreateRouteResponse
	(*GetRoutesRequest)(nil),           // 2: rtmgr.GetRoutesRequest
	(*GetRoutesResponse)(nil),          // 3: rtmgr.GetRoutesResponse
	(*GetRouteRequest)(nil),            // 4: rtmgr.GetRouteRequest
	(*GetRouteResponse)(nil),           // 5: rtmgr.GetRouteResponse
	(*UpdateRouteRequest)(nil),         // 6: rtmgr.UpdateRouteRequest
	(*UpdateRouteResponse)(nil),        // 7: rtmgr.UpdateRouteResponse
	(*DeleteRouteRequest)(nil),         // 8: rtmgr.DeleteRouteRequest
	(*DeleteRouteResponse)(nil),        // 9: rtmgr.DeleteRouteResponse
	(*GetRoutingTableRequest)(nil),     // 10: rtmgr.GetRoutingTableRequest
	(*GetRoutingTableResponse)(nil),    // 11: rtmgr.GetRoutingTableResponse
	(*UpdateRoutingTableRequest)(nil),  // 12: rtmgr.UpdateRoutingTableRequest
	(*UpdateRoutingTableResponse)(nil), // 13: rtmgr.UpdateRoutingTableResponse
	(*RegisterXAppRequest)(nil),        // 14: rtmgr.RegisterXAppRequest
	(*RegisterXAppResponse)(nil),       // 15: rtmgr.RegisterXAppResponse
	(*UnregisterXAppRequest)(nil),      // 16: rtmgr.UnregisterXAppRequest
	(*UnregisterXAppResponse)(nil),     // 17: rtmgr.UnregisterXAppResponse
	(*GetXAppsRequest)(nil),            // 18: rtmgr.GetXAppsRequest
	(*GetXAppsResponse)(nil),           // 19: rtmgr.GetXAppsResponse
	(*GetStatsRequest)(nil),            // 20: rtmgr.GetStatsRequest
	(*GetStatsResponse)(nil),           // 21: rtmgr.GetStatsResponse
	(*GetHealthRequest)(nil),           // 22: rtmgr.GetHealthRequest
	(*GetHealthResponse)(nil),          // 23: rtmgr.GetHealthResponse
	(*Route)(nil),                      // 24: rtmgr.Route
	(*RoutePolicy)(nil),                // 25: rtmgr.RoutePolicy
	(*RoutingTable)(nil),               // 26: rtmgr.RoutingTable
	(*RouteEntry)(nil),                 // 27: rtmgr.RouteEntry
	(*XAppInfo)(nil),                   // 28: rtmgr.XAppInfo
	(*RoutingStats)(nil),               // 29: rtmgr.RoutingStats
	(*RoutingHealth)(nil),              // 30: rtmgr.RoutingHealth
	nil,                                // 31: rtmgr.RoutePolicy.ParametersEntry
	nil,                                // 32: rtmgr.XAppInfo.ConfigEntry
	nil,                                // 33: rtmgr.RoutingStats.RoutesByMessageTypeEntry
	nil,                                // 34: rtmgr.RoutingStats.XappsByStatusEntry
	(*timestamppb.Timestamp)(nil),      // 35: google.protobuf.Timestamp
}
var file_api_proto_rtmgr_rtmgr_proto_depIdxs = []int32{
	24, // 0: rtmgr.CreateRouteRequest.route:type_name -> rtmgr.Route
	24, // 1: rtmgr.GetRoutesResponse.routes:type_name -> rtmgr.Route
	24, // 2: rtmgr.GetRouteResponse.route:type_name -> rtmgr.Route
	24, // 3: rtmgr.UpdateRouteRequest.route:type_name -> rtmgr.Route
	26, // 4: rtmgr.GetRoutingTableResponse.routing_table:type_name -> rtmgr.RoutingTable
	26, // 5: rtmgr.UpdateRoutingTableRequest.routing_table:type_name -> rtmgr.RoutingTable
	28, // 6: rtmgr.RegisterXAppRequest.xapp_info:type_name -> rtmgr.XAppInfo
	28, // 7: rtmgr.GetXAppsResponse.xapps:type_name -> rtmgr.XAppInfo
	29, // 8: rtmgr.GetStatsResponse.stats:type_name -> rtmgr.RoutingStats
	30, // 9: rtmgr.GetHealthResponse.health:type_name -> rtmgr.RoutingHealth
	25, // 10: rtmgr.Route.policy:type_name -> rtmgr.RoutePolicy
	35, // 11: rtmgr.Route.created_at:type_name -> google.protobuf.Timestamp
	35, // 12: rtmgr.Route.updated_at:type_name -> google.protobuf.Timestamp
	31, // 13: rtmgr.RoutePolicy.parameters:type_name -> rtmgr.RoutePolicy.ParametersEntry
	27, // 14: rtmgr.RoutingTable.entries:type_name -> rtmgr.RouteEntry
	35, // 15: rtmgr.RoutingTable.last_updated:type_name -> google.protobuf.Timestamp
	25, // 16: rtmgr.RouteEntry.policy:type_name -> rtmgr.RoutePolicy
	32, // 17: rtmgr.XAppInfo.config:type_name -> rtmgr.XAppInfo.ConfigEntry
	35, // 18: rtmgr.XAppInfo.registered_at:type_name -> google.protobuf.Timestamp
	35, // 19: rtmgr.XAppInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	33, // 20: rtmgr.RoutingStats.routes_by_message_type:type_name -> rtmgr.RoutingStats.RoutesByMessageTypeEntry
	34, // 21: rtmgr.RoutingStats.xapps_by_status:type_name -> rtmgr.RoutingStats.XappsByStatusEntry
	35, // 22: rtmgr.RoutingStats.last_updated:type_name -> google.protobuf.Timestamp
	35, // 23: rtmgr.RoutingHealth.last_health_check:type_name -> google.protobuf.Timestamp
	0,  // 24: rtmgr.RoutingManager.CreateRoute:input_type -> rtmgr.CreateRouteRequest
	2,  // 25: rtmgr.RoutingManager.GetRoutes:input_type -> rtmgr.GetRoutesRequest
	4,  // 26: rtmgr.RoutingManager.GetRoute:input_type -> rtmgr.GetRouteRequest
	6,  // 27: rtmgr.RoutingManager.UpdateRoute:input_type -> rtmgr.UpdateRouteRequest
	8,  // 28: rtmgr.RoutingManager.DeleteRoute:input_type -> rtmgr.DeleteRouteRequest
	10, // 29: rtmgr.RoutingManager.GetRoutingTable:input_type -> rtmgr.GetRoutingTableRequest
	12, // 30: rtmgr.RoutingManager.UpdateRoutingTable:input_type -> rtmgr.UpdateRoutingTableRequest
	14, // 31: rtmgr.RoutingManager.RegisterXApp:input_type -> rtmgr.RegisterXAppRequest
	16, // 32: rtmgr.RoutingManager.UnregisterXApp:input_type -> rtmgr.UnregisterXAppRequest
	18, // 33: rtmgr.RoutingManager.GetXApps:input_type -> rtmgr.GetXAppsRequest
	20, // 34: rtmgr.RoutingManager.GetStats:input_type -> rtmgr.GetStatsRequest
	22, // 35: rtmgr.RoutingManager.GetHealth:input_type -> rtmgr.GetHealthRequest
	1,  // 36: rtmgr.RoutingManager.CreateRoute:output_type -> rtmgr.CreateRouteResponse
	3,  // 37: rtmgr.RoutingManager.GetRoutes:output_type -> rtmgr.GetRoutesResponse
	5,  // 38: rtmgr.RoutingManager.GetRoute:output_type -> rtmgr.GetRouteResponse
	7,  // 39: rtmgr.RoutingManager.UpdateRoute:output_type -> rtmgr.UpdateRouteResponse
	9,  // 40: rtmgr.RoutingManager.DeleteRoute:output_type -> rtmgr.DeleteRouteResponse
	11, // 41: rtmgr.RoutingManager.GetRoutingTable:output_type -> rtmgr.GetRoutingTableResponse
	13, // 42: rtmgr.RoutingManager.UpdateRoutingTable:output_type -> rtmgr.UpdateRoutingTableResponse
	15, // 43: rtmgr.RoutingManager.RegisterXApp:output_type -> rtmgr.RegisterXAppResponse
	17, // 44: rtmgr.RoutingManager.UnregisterXApp:output_type -> rtmgr.UnregisterXAppResponse
	19, // 45: rtmgr.RoutingManager.GetXApps:output_type -> rtmgr.GetXAppsResponse
	21, // 46: rtmgr.RoutingManager.GetStats:output_type -> rtmgr.GetStatsResponse
	23, // 47: rtmgr.RoutingManager.GetHealth:output_type -> rtmgr.GetHealthResponse
	36, // [36:48] is the sub-list for method output_type
	24, // [24:36] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_proto_rtmgr_rtmgr_proto_init() }
func file_api_proto_rtmgr_rtmgr_proto_init() {
	if File_api_proto_rtmgr_rtmgr_proto != nil {
		return
	}
	file_api_proto_rtmgr_rtmgr_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_rtmgr_rtmgr_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rtmgr_rtmgr_proto_rawDesc), len(file_api_proto_rtmgr_rtmgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rtmgr_rtmgr_proto_goTypes,
		DependencyIndexes: file_api_proto_rtmgr_rtmgr_proto_depIdxs,
		MessageInfos:      file_api_proto_rtmgr_rtmgr_proto_msgTypes,
	}.Build()
	File_api_proto_rtmgr_rtmgr_proto = out.File
	file_api_proto_rtmgr_rtmgr_proto_goTypes = nil
	file_api_proto_rtmgr_rtmgr_proto_depIdxs = nil
}
