// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/rtmgr/rtmgr.proto

package rtmgr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoutingManagerClient is the client API for RoutingManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutingManagerClient interface {
	// Route management operations
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error)
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
	UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	// Routing table operations
	GetRoutingTable(ctx context.Context, in *GetRoutingTableRequest, opts ...grpc.CallOption) (*GetRoutingTableResponse, error)
	UpdateRoutingTable(ctx context.Context, in *UpdateRoutingTableRequest, opts ...grpc.CallOption) (*UpdateRoutingTableResponse, error)
	// xApp registration and discovery
	RegisterXApp(ctx context.Context, in *RegisterXAppRequest, opts ...grpc.CallOption) (*RegisterXAppResponse, error)
	UnregisterXApp(ctx context.Context, in *UnregisterXAppRequest, opts ...grpc.CallOption) (*UnregisterXAppResponse, error)
	GetXApps(ctx context.Context, in *GetXAppsRequest, opts ...grpc.CallOption) (*GetXAppsResponse, error)
	// Health and statistics
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
}

type routingManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingManagerClient(cc grpc.ClientConnInterface) RoutingManagerClient {
	return &routingManagerClient{cc}
}

func (c *routingManagerClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error) {
	out := new(CreateRouteResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/CreateRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/GetRoutes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/GetRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error) {
	out := new(UpdateRouteResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/UpdateRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/DeleteRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetRoutingTable(ctx context.Context, in *GetRoutingTableRequest, opts ...grpc.CallOption) (*GetRoutingTableResponse, error) {
	out := new(GetRoutingTableResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/GetRoutingTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) UpdateRoutingTable(ctx context.Context, in *UpdateRoutingTableRequest, opts ...grpc.CallOption) (*UpdateRoutingTableResponse, error) {
	out := new(UpdateRoutingTableResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/UpdateRoutingTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) RegisterXApp(ctx context.Context, in *RegisterXAppRequest, opts ...grpc.CallOption) (*RegisterXAppResponse, error) {
	out := new(RegisterXAppResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/RegisterXApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) UnregisterXApp(ctx context.Context, in *UnregisterXAppRequest, opts ...grpc.CallOption) (*UnregisterXAppResponse, error) {
	out := new(UnregisterXAppResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/UnregisterXApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetXApps(ctx context.Context, in *GetXAppsRequest, opts ...grpc.CallOption) (*GetXAppsResponse, error) {
	out := new(GetXAppsResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/GetXApps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingManagerClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, "/rtmgr.RoutingManager/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingManagerServer is the server API for RoutingManager service.
// All implementations must embed UnimplementedRoutingManagerServer
// for forward compatibility
type RoutingManagerServer interface {
	// Route management operations
	CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error)
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	// Routing table operations
	GetRoutingTable(context.Context, *GetRoutingTableRequest) (*GetRoutingTableResponse, error)
	UpdateRoutingTable(context.Context, *UpdateRoutingTableRequest) (*UpdateRoutingTableResponse, error)
	// xApp registration and discovery
	RegisterXApp(context.Context, *RegisterXAppRequest) (*RegisterXAppResponse, error)
	UnregisterXApp(context.Context, *UnregisterXAppRequest) (*UnregisterXAppResponse, error)
	GetXApps(context.Context, *GetXAppsRequest) (*GetXAppsResponse, error)
	// Health and statistics
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	mustEmbedUnimplementedRoutingManagerServer()
}

// UnimplementedRoutingManagerServer must be embedded to have forward compatible implementations.
type UnimplementedRoutingManagerServer struct {
}

func (UnimplementedRoutingManagerServer) CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedRoutingManagerServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedRoutingManagerServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedRoutingManagerServer) UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoute not implemented")
}
func (UnimplementedRoutingManagerServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedRoutingManagerServer) GetRoutingTable(context.Context, *GetRoutingTableRequest) (*GetRoutingTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingTable not implemented")
}
func (UnimplementedRoutingManagerServer) UpdateRoutingTable(context.Context, *UpdateRoutingTableRequest) (*UpdateRoutingTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoutingTable not implemented")
}
func (UnimplementedRoutingManagerServer) RegisterXApp(context.Context, *RegisterXAppRequest) (*RegisterXAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterXApp not implemented")
}
func (UnimplementedRoutingManagerServer) UnregisterXApp(context.Context, *UnregisterXAppRequest) (*UnregisterXAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterXApp not implemented")
}
func (UnimplementedRoutingManagerServer) GetXApps(context.Context, *GetXAppsRequest) (*GetXAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetXApps not implemented")
}
func (UnimplementedRoutingManagerServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedRoutingManagerServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedRoutingManagerServer) mustEmbedUnimplementedRoutingManagerServer() {}

// UnsafeRoutingManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingManagerServer will
// result in compilation errors.
type UnsafeRoutingManagerServer interface {
	mustEmbedUnimplementedRoutingManagerServer()
}

func RegisterRoutingManagerServer(s grpc.ServiceRegistrar, srv RoutingManagerServer) {
	s.RegisterService(&RoutingManager_ServiceDesc, srv)
}

// RoutingManager_ServiceDesc is the grpc.ServiceDesc for RoutingManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtmgr.RoutingManager",
	HandlerType: (*RoutingManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoute",
			Handler:    nil, // Handler implementation would be here
		},
		// Additional method descriptors would be here in real implementation
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/rtmgr/rtmgr.proto",
}