// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/proto/rtmgr/rtmgr.proto

package rtmgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateRouteRequest represents a request to create a new route
type CreateRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

// CreateRouteResponse represents the response to a route creation request
type CreateRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteId string `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateRouteResponse) Reset() {
	*x = CreateRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteResponse) ProtoMessage() {}

func (x *CreateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteResponse.ProtoReflect.Descriptor instead.
func (*CreateRouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRouteResponse) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CreateRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRouteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Route represents a routing rule in the system
type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceXapp     string                 `protobuf:"bytes,2,opt,name=source_xapp,json=sourceXapp,proto3" json:"source_xapp,omitempty"`
	TargetXapp     string                 `protobuf:"bytes,3,opt,name=target_xapp,json=targetXapp,proto3" json:"target_xapp,omitempty"`
	MessageType    uint32                 `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,5,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Policy         *RoutePolicy           `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetSourceXapp() string {
	if x != nil {
		return x.SourceXapp
	}
	return ""
}

func (x *Route) GetTargetXapp() string {
	if x != nil {
		return x.TargetXapp
	}
	return ""
}

func (x *Route) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *Route) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Route) GetPolicy() *RoutePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Route) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Route) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RoutePolicy represents routing policy configuration
type RoutePolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RoutePolicy) Reset() {
	*x = RoutePolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicy) ProtoMessage() {}

func (x *RoutePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicy.ProtoReflect.Descriptor instead.
func (*RoutePolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{3}
}

func (x *RoutePolicy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RoutePolicy) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// XAppInfo represents information about a registered xApp
type XAppInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Namespace      string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Endpoints      []string               `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Config         map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RegisteredAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
}

func (x *XAppInfo) Reset() {
	*x = XAppInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAppInfo) ProtoMessage() {}

func (x *XAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rtmgr_rtmgr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAppInfo.ProtoReflect.Descriptor instead.
func (*XAppInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP(), []int{4}
}

func (x *XAppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *XAppInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *XAppInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *XAppInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *XAppInfo) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *XAppInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *XAppInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *XAppInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

var File_api_proto_rtmgr_rtmgr_proto protoreflect.FileDescriptor

var file_api_proto_rtmgr_rtmgr_proto_rawDesc = []byte{
	// Simplified descriptor - in real implementation this would be much longer
}

var (
	file_api_proto_rtmgr_rtmgr_proto_rawDescOnce sync.Once
	file_api_proto_rtmgr_rtmgr_proto_rawDescData = file_api_proto_rtmgr_rtmgr_proto_rawDesc
)

func file_api_proto_rtmgr_rtmgr_proto_rawDescGZIP() []byte {
	file_api_proto_rtmgr_rtmgr_proto_rawDescOnce.Do(func() {
		file_api_proto_rtmgr_rtmgr_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rtmgr_rtmgr_proto_rawDescData)
	})
	return file_api_proto_rtmgr_rtmgr_proto_rawDescData
}

var file_api_proto_rtmgr_rtmgr_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_rtmgr_rtmgr_proto_goTypes = []interface{}{
	(*CreateRouteRequest)(nil),      // 0: rtmgr.CreateRouteRequest
	(*CreateRouteResponse)(nil),     // 1: rtmgr.CreateRouteResponse
	(*Route)(nil),                   // 2: rtmgr.Route
	(*RoutePolicy)(nil),             // 3: rtmgr.RoutePolicy
	(*XAppInfo)(nil),                // 4: rtmgr.XAppInfo
	nil,                             // 5: rtmgr.RoutePolicy.ParametersEntry
	nil,                             // 6: rtmgr.XAppInfo.ConfigEntry
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}

var file_api_proto_rtmgr_rtmgr_proto_depIdxs = []int32{
	2, // 0: rtmgr.CreateRouteRequest.route:type_name -> rtmgr.Route
	3, // 1: rtmgr.Route.policy:type_name -> rtmgr.RoutePolicy
	7, // 2: rtmgr.Route.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: rtmgr.Route.updated_at:type_name -> google.protobuf.Timestamp
	5, // 4: rtmgr.RoutePolicy.parameters:type_name -> rtmgr.RoutePolicy.ParametersEntry
	6, // 5: rtmgr.XAppInfo.config:type_name -> rtmgr.XAppInfo.ConfigEntry
	7, // 6: rtmgr.XAppInfo.registered_at:type_name -> google.protobuf.Timestamp
	7, // 7: rtmgr.XAppInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_rtmgr_rtmgr_proto_init() }
func file_api_proto_rtmgr_rtmgr_proto_init() {
	if File_api_proto_rtmgr_rtmgr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_rtmgr_rtmgr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		// Additional message type exporters would be here in real implementation
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rtmgr_rtmgr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rtmgr_rtmgr_proto_goTypes,
		DependencyIndexes: file_api_proto_rtmgr_rtmgr_proto_depIdxs,
		MessageInfos:      file_api_proto_rtmgr_rtmgr_proto_msgTypes,
	}.Build()
	File_api_proto_rtmgr_rtmgr_proto = out.File
	file_api_proto_rtmgr_rtmgr_proto_rawDesc = nil
	file_api_proto_rtmgr_rtmgr_proto_goTypes = nil
	file_api_proto_rtmgr_rtmgr_proto_depIdxs = nil
}