{{- if .Values.global.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    platform: {{ .Values.global.labels.platform }}
    release: {{ .Values.global.labels.release }}
    app.kubernetes.io/name: {{ include "oran-sc-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    description: "O-RAN SC Near-RT RIC Platform Namespace"
{{- end }}