// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.1
// source: api/proto/slicemgr/slice_management.proto

package slicemgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums for Slice Types and States
type SliceType int32

const (
	SliceType_EMBB  SliceType = 0
	SliceType_URLLC SliceType = 1
	SliceType_MMTC  SliceType = 2
)

// Enum value maps for SliceType.
var (
	SliceType_name = map[int32]string{
		0: "EMBB",
		1: "URLLC",
		2: "MMTC",
	}
	SliceType_value = map[string]int32{
		"EMBB":  0,
		"URLLC": 1,
		"MMTC":  2,
	}
)

func (x SliceType) Enum() *SliceType {
	p := new(SliceType)
	*p = x
	return p
}

func (x SliceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SliceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_slicemgr_slice_management_proto_enumTypes[0].Descriptor()
}

func (SliceType) Type() protoreflect.EnumType {
	return &file_api_proto_slicemgr_slice_management_proto_enumTypes[0]
}

func (x SliceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SliceType.Descriptor instead.
func (SliceType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{0}
}

type SliceState int32

const (
	SliceState_CREATED     SliceState = 0
	SliceState_ACTIVE      SliceState = 1
	SliceState_INACTIVE    SliceState = 2
	SliceState_SCALING     SliceState = 3
	SliceState_FAILED      SliceState = 4
	SliceState_TERMINATING SliceState = 5
)

// Enum value maps for SliceState.
var (
	SliceState_name = map[int32]string{
		0: "CREATED",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "SCALING",
		4: "FAILED",
		5: "TERMINATING",
	}
	SliceState_value = map[string]int32{
		"CREATED":     0,
		"ACTIVE":      1,
		"INACTIVE":    2,
		"SCALING":     3,
		"FAILED":      4,
		"TERMINATING": 5,
	}
)

func (x SliceState) Enum() *SliceState {
	p := new(SliceState)
	*p = x
	return p
}

func (x SliceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SliceState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_slicemgr_slice_management_proto_enumTypes[1].Descriptor()
}

func (SliceState) Type() protoreflect.EnumType {
	return &file_api_proto_slicemgr_slice_management_proto_enumTypes[1]
}

func (x SliceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SliceState.Descriptor instead.
func (SliceState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{1}
}

type PolicyType int32

const (
	PolicyType_QOS                  PolicyType = 0
	PolicyType_RAN_SLICE            PolicyType = 1
	PolicyType_RESOURCE_UTILIZATION PolicyType = 2
)

// Enum value maps for PolicyType.
var (
	PolicyType_name = map[int32]string{
		0: "QOS",
		1: "RAN_SLICE",
		2: "RESOURCE_UTILIZATION",
	}
	PolicyType_value = map[string]int32{
		"QOS":                  0,
		"RAN_SLICE":            1,
		"RESOURCE_UTILIZATION": 2,
	}
)

func (x PolicyType) Enum() *PolicyType {
	p := new(PolicyType)
	*p = x
	return p
}

func (x PolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_slicemgr_slice_management_proto_enumTypes[2].Descriptor()
}

func (PolicyType) Type() protoreflect.EnumType {
	return &file_api_proto_slicemgr_slice_management_proto_enumTypes[2]
}

func (x PolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyType.Descriptor instead.
func (PolicyType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{2}
}

// Slice Definition
type Slice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           SliceType              `protobuf:"varint,3,opt,name=type,proto3,enum=slicemgr.SliceType" json:"type,omitempty"`
	State          SliceState             `protobuf:"varint,4,opt,name=state,proto3,enum=slicemgr.SliceState" json:"state,omitempty"`
	Tenant         string                 `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ServiceProfile *ServiceProfile        `protobuf:"bytes,6,opt,name=service_profile,json=serviceProfile,proto3" json:"service_profile,omitempty"`
	ResourceQuota  *ResourceQuota         `protobuf:"bytes,7,opt,name=resource_quota,json=resourceQuota,proto3" json:"resource_quota,omitempty"`
	Sla            *SliceSLA              `protobuf:"bytes,8,opt,name=sla,proto3" json:"sla,omitempty"`
	Placement      *PlacementPolicy       `protobuf:"bytes,9,opt,name=placement,proto3" json:"placement,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Slice) Reset() {
	*x = Slice{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{0}
}

func (x *Slice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Slice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Slice) GetType() SliceType {
	if x != nil {
		return x.Type
	}
	return SliceType_EMBB
}

func (x *Slice) GetState() SliceState {
	if x != nil {
		return x.State
	}
	return SliceState_CREATED
}

func (x *Slice) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Slice) GetServiceProfile() *ServiceProfile {
	if x != nil {
		return x.ServiceProfile
	}
	return nil
}

func (x *Slice) GetResourceQuota() *ResourceQuota {
	if x != nil {
		return x.ResourceQuota
	}
	return nil
}

func (x *Slice) GetSla() *SliceSLA {
	if x != nil {
		return x.Sla
	}
	return nil
}

func (x *Slice) GetPlacement() *PlacementPolicy {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *Slice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Slice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Detailed Slice Structures
type ServiceProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxDataRate      *DataRate              `protobuf:"bytes,1,opt,name=max_data_rate,json=maxDataRate,proto3" json:"max_data_rate,omitempty"`
	Latency          int32                  `protobuf:"varint,2,opt,name=latency,proto3" json:"latency,omitempty"`
	Reliability      float32                `protobuf:"fixed32,3,opt,name=reliability,proto3" json:"reliability,omitempty"`
	MaxConcurrentUes int32                  `protobuf:"varint,4,opt,name=max_concurrent_ues,json=maxConcurrentUes,proto3" json:"max_concurrent_ues,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceProfile) Reset() {
	*x = ServiceProfile{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceProfile) ProtoMessage() {}

func (x *ServiceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceProfile.ProtoReflect.Descriptor instead.
func (*ServiceProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceProfile) GetMaxDataRate() *DataRate {
	if x != nil {
		return x.MaxDataRate
	}
	return nil
}

func (x *ServiceProfile) GetLatency() int32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *ServiceProfile) GetReliability() float32 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

func (x *ServiceProfile) GetMaxConcurrentUes() int32 {
	if x != nil {
		return x.MaxConcurrentUes
	}
	return 0
}

type DataRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Downlink      int32                  `protobuf:"varint,1,opt,name=downlink,proto3" json:"downlink,omitempty"`
	Uplink        int32                  `protobuf:"varint,2,opt,name=uplink,proto3" json:"uplink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRate) Reset() {
	*x = DataRate{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRate) ProtoMessage() {}

func (x *DataRate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRate.ProtoReflect.Descriptor instead.
func (*DataRate) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{2}
}

func (x *DataRate) GetDownlink() int32 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *DataRate) GetUplink() int32 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

type ResourceQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compute       *ComputeResources      `protobuf:"bytes,1,opt,name=compute,proto3" json:"compute,omitempty"`
	Network       *NetworkResources      `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Storage       *StorageResources      `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceQuota) Reset() {
	*x = ResourceQuota{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceQuota) ProtoMessage() {}

func (x *ResourceQuota) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceQuota.ProtoReflect.Descriptor instead.
func (*ResourceQuota) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceQuota) GetCompute() *ComputeResources {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *ResourceQuota) GetNetwork() *NetworkResources {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ResourceQuota) GetStorage() *StorageResources {
	if x != nil {
		return x.Storage
	}
	return nil
}

type ComputeResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPUResource           `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryResource        `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeResources) Reset() {
	*x = ComputeResources{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResources) ProtoMessage() {}

func (x *ComputeResources) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResources.ProtoReflect.Descriptor instead.
func (*ComputeResources) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{4}
}

func (x *ComputeResources) GetCpu() *CPUResource {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *ComputeResources) GetMemory() *MemoryResource {
	if x != nil {
		return x.Memory
	}
	return nil
}

type CPUResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUResource) Reset() {
	*x = CPUResource{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUResource) ProtoMessage() {}

func (x *CPUResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUResource.ProtoReflect.Descriptor instead.
func (*CPUResource) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{5}
}

func (x *CPUResource) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *CPUResource) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type MemoryResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResource) Reset() {
	*x = MemoryResource{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResource) ProtoMessage() {}

func (x *MemoryResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResource.ProtoReflect.Descriptor instead.
func (*MemoryResource) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryResource) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *MemoryResource) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type NetworkResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bandwidth     *Bandwidth             `protobuf:"bytes,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Vlans         []int32                `protobuf:"varint,2,rep,packed,name=vlans,proto3" json:"vlans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkResources) Reset() {
	*x = NetworkResources{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkResources) ProtoMessage() {}

func (x *NetworkResources) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkResources.ProtoReflect.Descriptor instead.
func (*NetworkResources) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkResources) GetBandwidth() *Bandwidth {
	if x != nil {
		return x.Bandwidth
	}
	return nil
}

func (x *NetworkResources) GetVlans() []int32 {
	if x != nil {
		return x.Vlans
	}
	return nil
}

type Bandwidth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Guaranteed    int32                  `protobuf:"varint,2,opt,name=guaranteed,proto3" json:"guaranteed,omitempty"`
	Max           int32                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bandwidth) Reset() {
	*x = Bandwidth{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bandwidth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bandwidth) ProtoMessage() {}

func (x *Bandwidth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bandwidth.ProtoReflect.Descriptor instead.
func (*Bandwidth) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{8}
}

func (x *Bandwidth) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Bandwidth) GetGuaranteed() int32 {
	if x != nil {
		return x.Guaranteed
	}
	return 0
}

func (x *Bandwidth) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type StorageResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int32                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Iops          int32                  `protobuf:"varint,2,opt,name=iops,proto3" json:"iops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResources) Reset() {
	*x = StorageResources{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResources) ProtoMessage() {}

func (x *StorageResources) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResources.ProtoReflect.Descriptor instead.
func (*StorageResources) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{9}
}

func (x *StorageResources) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StorageResources) GetIops() int32 {
	if x != nil {
		return x.Iops
	}
	return 0
}

type SliceSLA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objectives    *SLAObjectives         `protobuf:"bytes,1,opt,name=objectives,proto3" json:"objectives,omitempty"`
	Monitoring    *MonitoringConfig      `protobuf:"bytes,2,opt,name=monitoring,proto3" json:"monitoring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceSLA) Reset() {
	*x = SliceSLA{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceSLA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceSLA) ProtoMessage() {}

func (x *SliceSLA) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceSLA.ProtoReflect.Descriptor instead.
func (*SliceSLA) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{10}
}

func (x *SliceSLA) GetObjectives() *SLAObjectives {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *SliceSLA) GetMonitoring() *MonitoringConfig {
	if x != nil {
		return x.Monitoring
	}
	return nil
}

type SLAObjectives struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Throughput    *Throughput            `protobuf:"bytes,1,opt,name=throughput,proto3" json:"throughput,omitempty"`
	Latency       *Latency               `protobuf:"bytes,2,opt,name=latency,proto3" json:"latency,omitempty"`
	Reliability   float32                `protobuf:"fixed32,3,opt,name=reliability,proto3" json:"reliability,omitempty"`
	PacketLoss    float32                `protobuf:"fixed32,4,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLAObjectives) Reset() {
	*x = SLAObjectives{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLAObjectives) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAObjectives) ProtoMessage() {}

func (x *SLAObjectives) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAObjectives.ProtoReflect.Descriptor instead.
func (*SLAObjectives) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{11}
}

func (x *SLAObjectives) GetThroughput() *Throughput {
	if x != nil {
		return x.Throughput
	}
	return nil
}

func (x *SLAObjectives) GetLatency() *Latency {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *SLAObjectives) GetReliability() float32 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

func (x *SLAObjectives) GetPacketLoss() float32 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

type Throughput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Downlink      *DataRate              `protobuf:"bytes,1,opt,name=downlink,proto3" json:"downlink,omitempty"`
	Uplink        *DataRate              `protobuf:"bytes,2,opt,name=uplink,proto3" json:"uplink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Throughput) Reset() {
	*x = Throughput{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Throughput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Throughput) ProtoMessage() {}

func (x *Throughput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Throughput.ProtoReflect.Descriptor instead.
func (*Throughput) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{12}
}

func (x *Throughput) GetDownlink() *DataRate {
	if x != nil {
		return x.Downlink
	}
	return nil
}

func (x *Throughput) GetUplink() *DataRate {
	if x != nil {
		return x.Uplink
	}
	return nil
}

type Latency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	E2E           *E2ELatency            `protobuf:"bytes,1,opt,name=e2e,proto3" json:"e2e,omitempty"`
	Ran           *RANLatency            `protobuf:"bytes,2,opt,name=ran,proto3" json:"ran,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Latency) Reset() {
	*x = Latency{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Latency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Latency) ProtoMessage() {}

func (x *Latency) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Latency.ProtoReflect.Descriptor instead.
func (*Latency) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{13}
}

func (x *Latency) GetE2E() *E2ELatency {
	if x != nil {
		return x.E2E
	}
	return nil
}

func (x *Latency) GetRan() *RANLatency {
	if x != nil {
		return x.Ran
	}
	return nil
}

type E2ELatency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int32                  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Maximum       int32                  `protobuf:"varint,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2ELatency) Reset() {
	*x = E2ELatency{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2ELatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2ELatency) ProtoMessage() {}

func (x *E2ELatency) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2ELatency.ProtoReflect.Descriptor instead.
func (*E2ELatency) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{14}
}

func (x *E2ELatency) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *E2ELatency) GetMaximum() int32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

type RANLatency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int32                  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Maximum       int32                  `protobuf:"varint,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RANLatency) Reset() {
	*x = RANLatency{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RANLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RANLatency) ProtoMessage() {}

func (x *RANLatency) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RANLatency.ProtoReflect.Descriptor instead.
func (*RANLatency) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{15}
}

func (x *RANLatency) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *RANLatency) GetMaximum() int32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

type MonitoringConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      int32                  `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Metrics       []string               `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringConfig) Reset() {
	*x = MonitoringConfig{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringConfig) ProtoMessage() {}

func (x *MonitoringConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringConfig.ProtoReflect.Descriptor instead.
func (*MonitoringConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{16}
}

func (x *MonitoringConfig) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *MonitoringConfig) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type PlacementPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*RegionPlacement     `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	Affinity      []*AffinityRule        `protobuf:"bytes,2,rep,name=affinity,proto3" json:"affinity,omitempty"`
	AntiAffinity  []*AffinityRule        `protobuf:"bytes,3,rep,name=anti_affinity,json=antiAffinity,proto3" json:"anti_affinity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementPolicy) Reset() {
	*x = PlacementPolicy{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementPolicy) ProtoMessage() {}

func (x *PlacementPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementPolicy.ProtoReflect.Descriptor instead.
func (*PlacementPolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{17}
}

func (x *PlacementPolicy) GetRegions() []*RegionPlacement {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *PlacementPolicy) GetAffinity() []*AffinityRule {
	if x != nil {
		return x.Affinity
	}
	return nil
}

func (x *PlacementPolicy) GetAntiAffinity() []*AffinityRule {
	if x != nil {
		return x.AntiAffinity
	}
	return nil
}

type RegionPlacement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Zones         []string               `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionPlacement) Reset() {
	*x = RegionPlacement{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionPlacement) ProtoMessage() {}

func (x *RegionPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionPlacement.ProtoReflect.Descriptor instead.
func (*RegionPlacement) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{18}
}

func (x *RegionPlacement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegionPlacement) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

type AffinityRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffinityRule) Reset() {
	*x = AffinityRule{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffinityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffinityRule) ProtoMessage() {}

func (x *AffinityRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffinityRule.ProtoReflect.Descriptor instead.
func (*AffinityRule) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{19}
}

func (x *AffinityRule) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AffinityRule) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *AffinityRule) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// Request/Response Messages for Slice Management
type CreateSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slice         *Slice                 `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSliceRequest) Reset() {
	*x = CreateSliceRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSliceRequest) ProtoMessage() {}

func (x *CreateSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSliceRequest.ProtoReflect.Descriptor instead.
func (*CreateSliceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{20}
}

func (x *CreateSliceRequest) GetSlice() *Slice {
	if x != nil {
		return x.Slice
	}
	return nil
}

type CreateSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slice         *Slice                 `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSliceResponse) Reset() {
	*x = CreateSliceResponse{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSliceResponse) ProtoMessage() {}

func (x *CreateSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSliceResponse.ProtoReflect.Descriptor instead.
func (*CreateSliceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSliceResponse) GetSlice() *Slice {
	if x != nil {
		return x.Slice
	}
	return nil
}

func (x *CreateSliceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSliceRequest) Reset() {
	*x = GetSliceRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSliceRequest) ProtoMessage() {}

func (x *GetSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSliceRequest.ProtoReflect.Descriptor instead.
func (*GetSliceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{22}
}

func (x *GetSliceRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

type ListSlicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Type          SliceType              `protobuf:"varint,2,opt,name=type,proto3,enum=slicemgr.SliceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesRequest) Reset() {
	*x = ListSlicesRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesRequest) ProtoMessage() {}

func (x *ListSlicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesRequest.ProtoReflect.Descriptor instead.
func (*ListSlicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{23}
}

func (x *ListSlicesRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ListSlicesRequest) GetType() SliceType {
	if x != nil {
		return x.Type
	}
	return SliceType_EMBB
}

type ListSlicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slices        []*Slice               `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesResponse) Reset() {
	*x = ListSlicesResponse{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesResponse) ProtoMessage() {}

func (x *ListSlicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesResponse.ProtoReflect.Descriptor instead.
func (*ListSlicesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{24}
}

func (x *ListSlicesResponse) GetSlices() []*Slice {
	if x != nil {
		return x.Slices
	}
	return nil
}

type UpdateSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	UpdatedSlice  *Slice                 `protobuf:"bytes,2,opt,name=updated_slice,json=updatedSlice,proto3" json:"updated_slice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSliceRequest) Reset() {
	*x = UpdateSliceRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSliceRequest) ProtoMessage() {}

func (x *UpdateSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSliceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSliceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateSliceRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *UpdateSliceRequest) GetUpdatedSlice() *Slice {
	if x != nil {
		return x.UpdatedSlice
	}
	return nil
}

type DeleteSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSliceRequest) Reset() {
	*x = DeleteSliceRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSliceRequest) ProtoMessage() {}

func (x *DeleteSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSliceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSliceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteSliceRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

type DeleteSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSliceResponse) Reset() {
	*x = DeleteSliceResponse{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSliceResponse) ProtoMessage() {}

func (x *DeleteSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSliceResponse.ProtoReflect.Descriptor instead.
func (*DeleteSliceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteSliceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSliceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Policy Management Messages
type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Type          PolicyType             `protobuf:"varint,2,opt,name=type,proto3,enum=slicemgr.PolicyType" json:"type,omitempty"`
	PolicyData    *structpb.Struct       `protobuf:"bytes,3,opt,name=policy_data,json=policyData,proto3" json:"policy_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{28}
}

func (x *CreatePolicyRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *CreatePolicyRequest) GetType() PolicyType {
	if x != nil {
		return x.Type
	}
	return PolicyType_QOS
}

func (x *CreatePolicyRequest) GetPolicyData() *structpb.Struct {
	if x != nil {
		return x.PolicyData
	}
	return nil
}

type SlicePolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SliceId        string                 `protobuf:"bytes,2,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Type           PolicyType             `protobuf:"varint,3,opt,name=type,proto3,enum=slicemgr.PolicyType" json:"type,omitempty"`
	PolicyInstance *structpb.Struct       `protobuf:"bytes,4,opt,name=policy_instance,json=policyInstance,proto3" json:"policy_instance,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SlicePolicy) Reset() {
	*x = SlicePolicy{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlicePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlicePolicy) ProtoMessage() {}

func (x *SlicePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlicePolicy.ProtoReflect.Descriptor instead.
func (*SlicePolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{29}
}

func (x *SlicePolicy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SlicePolicy) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *SlicePolicy) GetType() PolicyType {
	if x != nil {
		return x.Type
	}
	return PolicyType_QOS
}

func (x *SlicePolicy) GetPolicyInstance() *structpb.Struct {
	if x != nil {
		return x.PolicyInstance
	}
	return nil
}

func (x *SlicePolicy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SlicePolicy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{30}
}

func (x *GetPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	UpdatedPolicy *structpb.Struct       `protobuf:"bytes,2,opt,name=updated_policy,json=updatedPolicy,proto3" json:"updated_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{31}
}

func (x *UpdatePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UpdatePolicyRequest) GetUpdatedPolicy() *structpb.Struct {
	if x != nil {
		return x.UpdatedPolicy
	}
	return nil
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{32}
}

func (x *DeletePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{33}
}

func (x *DeletePolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// E2 Node Integration Messages
type RegisterE2NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterE2NodeRequest) Reset() {
	*x = RegisterE2NodeRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterE2NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterE2NodeRequest) ProtoMessage() {}

func (x *RegisterE2NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterE2NodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterE2NodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{34}
}

func (x *RegisterE2NodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterE2NodeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterE2NodeRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterE2NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterE2NodeResponse) Reset() {
	*x = RegisterE2NodeResponse{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterE2NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterE2NodeResponse) ProtoMessage() {}

func (x *RegisterE2NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterE2NodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterE2NodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{35}
}

func (x *RegisterE2NodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterE2NodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigureSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SliceConfig   *Slice                 `protobuf:"bytes,3,opt,name=slice_config,json=sliceConfig,proto3" json:"slice_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSliceRequest) Reset() {
	*x = ConfigureSliceRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSliceRequest) ProtoMessage() {}

func (x *ConfigureSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSliceRequest.ProtoReflect.Descriptor instead.
func (*ConfigureSliceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{36}
}

func (x *ConfigureSliceRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *ConfigureSliceRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConfigureSliceRequest) GetSliceConfig() *Slice {
	if x != nil {
		return x.SliceConfig
	}
	return nil
}

type ConfigureSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSliceResponse) Reset() {
	*x = ConfigureSliceResponse{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSliceResponse) ProtoMessage() {}

func (x *ConfigureSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSliceResponse.ProtoReflect.Descriptor instead.
func (*ConfigureSliceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{37}
}

func (x *ConfigureSliceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureSliceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type E2NodeCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2NodeCapabilitiesRequest) Reset() {
	*x = E2NodeCapabilitiesRequest{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2NodeCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeCapabilitiesRequest) ProtoMessage() {}

func (x *E2NodeCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*E2NodeCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{38}
}

func (x *E2NodeCapabilitiesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type E2NodeCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2NodeCapabilitiesResponse) Reset() {
	*x = E2NodeCapabilitiesResponse{}
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2NodeCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeCapabilitiesResponse) ProtoMessage() {}

func (x *E2NodeCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_slicemgr_slice_management_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*E2NodeCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_slicemgr_slice_management_proto_rawDescGZIP(), []int{39}
}

func (x *E2NodeCapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_api_proto_slicemgr_slice_management_proto protoreflect.FileDescriptor

const file_api_proto_slicemgr_slice_management_proto_rawDesc = "" +
	"\n" +
	")api/proto/slicemgr/slice_management.proto\x12\bslicemgr\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf0\x03\n" +
	"\x05Slice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.slicemgr.SliceTypeR\x04type\x12*\n" +
	"\x05state\x18\x04 \x01(\x0e2\x14.slicemgr.SliceStateR\x05state\x12\x16\n" +
	"\x06tenant\x18\x05 \x01(\tR\x06tenant\x12A\n" +
	"\x0fservice_profile\x18\x06 \x01(\v2\x18.slicemgr.ServiceProfileR\x0eserviceProfile\x12>\n" +
	"\x0eresource_quota\x18\a \x01(\v2\x17.slicemgr.ResourceQuotaR\rresourceQuota\x12$\n" +
	"\x03sla\x18\b \x01(\v2\x12.slicemgr.SliceSLAR\x03sla\x127\n" +
	"\tplacement\x18\t \x01(\v2\x19.slicemgr.PlacementPolicyR\tplacement\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb2\x01\n" +
	"\x0eServiceProfile\x126\n" +
	"\rmax_data_rate\x18\x01 \x01(\v2\x12.slicemgr.DataRateR\vmaxDataRate\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x05R\alatency\x12 \n" +
	"\vreliability\x18\x03 \x01(\x02R\vreliability\x12,\n" +
	"\x12max_concurrent_ues\x18\x04 \x01(\x05R\x10maxConcurrentUes\">\n" +
	"\bDataRate\x12\x1a\n" +
	"\bdownlink\x18\x01 \x01(\x05R\bdownlink\x12\x16\n" +
	"\x06uplink\x18\x02 \x01(\x05R\x06uplink\"\xb1\x01\n" +
	"\rResourceQuota\x124\n" +
	"\acompute\x18\x01 \x01(\v2\x1a.slicemgr.ComputeResourcesR\acompute\x124\n" +
	"\anetwork\x18\x02 \x01(\v2\x1a.slicemgr.NetworkResourcesR\anetwork\x124\n" +
	"\astorage\x18\x03 \x01(\v2\x1a.slicemgr.StorageResourcesR\astorage\"m\n" +
	"\x10ComputeResources\x12'\n" +
	"\x03cpu\x18\x01 \x01(\v2\x15.slicemgr.CPUResourceR\x03cpu\x120\n" +
	"\x06memory\x18\x02 \x01(\v2\x18.slicemgr.MemoryResourceR\x06memory\"1\n" +
	"\vCPUResource\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"4\n" +
	"\x0eMemoryResource\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"[\n" +
	"\x10NetworkResources\x121\n" +
	"\tbandwidth\x18\x01 \x01(\v2\x13.slicemgr.BandwidthR\tbandwidth\x12\x14\n" +
	"\x05vlans\x18\x02 \x03(\x05R\x05vlans\"O\n" +
	"\tBandwidth\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x1e\n" +
	"\n" +
	"guaranteed\x18\x02 \x01(\x05R\n" +
	"guaranteed\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x05R\x03max\"B\n" +
	"\x10StorageResources\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\x12\x12\n" +
	"\x04iops\x18\x02 \x01(\x05R\x04iops\"\x7f\n" +
	"\bSliceSLA\x127\n" +
	"\n" +
	"objectives\x18\x01 \x01(\v2\x17.slicemgr.SLAObjectivesR\n" +
	"objectives\x12:\n" +
	"\n" +
	"monitoring\x18\x02 \x01(\v2\x1a.slicemgr.MonitoringConfigR\n" +
	"monitoring\"\xb5\x01\n" +
	"\rSLAObjectives\x124\n" +
	"\n" +
	"throughput\x18\x01 \x01(\v2\x14.slicemgr.ThroughputR\n" +
	"throughput\x12+\n" +
	"\alatency\x18\x02 \x01(\v2\x11.slicemgr.LatencyR\alatency\x12 \n" +
	"\vreliability\x18\x03 \x01(\x02R\vreliability\x12\x1f\n" +
	"\vpacket_loss\x18\x04 \x01(\x02R\n" +
	"packetLoss\"h\n" +
	"\n" +
	"Throughput\x12.\n" +
	"\bdownlink\x18\x01 \x01(\v2\x12.slicemgr.DataRateR\bdownlink\x12*\n" +
	"\x06uplink\x18\x02 \x01(\v2\x12.slicemgr.DataRateR\x06uplink\"Y\n" +
	"\aLatency\x12&\n" +
	"\x03e2e\x18\x01 \x01(\v2\x14.slicemgr.E2ELatencyR\x03e2e\x12&\n" +
	"\x03ran\x18\x02 \x01(\v2\x14.slicemgr.RANLatencyR\x03ran\">\n" +
	"\n" +
	"E2ELatency\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x05R\x06target\x12\x18\n" +
	"\amaximum\x18\x02 \x01(\x05R\amaximum\">\n" +
	"\n" +
	"RANLatency\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x05R\x06target\x12\x18\n" +
	"\amaximum\x18\x02 \x01(\x05R\amaximum\"H\n" +
	"\x10MonitoringConfig\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x05R\binterval\x12\x18\n" +
	"\ametrics\x18\x02 \x03(\tR\ametrics\"\xb7\x01\n" +
	"\x0fPlacementPolicy\x123\n" +
	"\aregions\x18\x01 \x03(\v2\x19.slicemgr.RegionPlacementR\aregions\x122\n" +
	"\baffinity\x18\x02 \x03(\v2\x16.slicemgr.AffinityRuleR\baffinity\x12;\n" +
	"\ranti_affinity\x18\x03 \x03(\v2\x16.slicemgr.AffinityRuleR\fantiAffinity\";\n" +
	"\x0fRegionPlacement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05zones\x18\x02 \x03(\tR\x05zones\"T\n" +
	"\fAffinityRule\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\";\n" +
	"\x12CreateSliceRequest\x12%\n" +
	"\x05slice\x18\x01 \x01(\v2\x0f.slicemgr.SliceR\x05slice\"V\n" +
	"\x13CreateSliceResponse\x12%\n" +
	"\x05slice\x18\x01 \x01(\v2\x0f.slicemgr.SliceR\x05slice\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x0fGetSliceRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\"T\n" +
	"\x11ListSlicesRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.slicemgr.SliceTypeR\x04type\"=\n" +
	"\x12ListSlicesResponse\x12'\n" +
	"\x06slices\x18\x01 \x03(\v2\x0f.slicemgr.SliceR\x06slices\"e\n" +
	"\x12UpdateSliceRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x124\n" +
	"\rupdated_slice\x18\x02 \x01(\v2\x0f.slicemgr.SliceR\fupdatedSlice\"/\n" +
	"\x12DeleteSliceRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\"I\n" +
	"\x13DeleteSliceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x01\n" +
	"\x13CreatePolicyRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.slicemgr.PolicyTypeR\x04type\x128\n" +
	"\vpolicy_data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"policyData\"\x9a\x02\n" +
	"\vSlicePolicy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bslice_id\x18\x02 \x01(\tR\asliceId\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.slicemgr.PolicyTypeR\x04type\x12@\n" +
	"\x0fpolicy_instance\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0epolicyInstance\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x10GetPolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"r\n" +
	"\x13UpdatePolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12>\n" +
	"\x0eupdated_policy\x18\x02 \x01(\v2\x17.google.protobuf.StructR\rupdatedPolicy\"2\n" +
	"\x13DeletePolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"J\n" +
	"\x14DeletePolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"s\n" +
	"\x15RegisterE2NodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"L\n" +
	"\x16RegisterE2NodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\x15ConfigureSliceRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x122\n" +
	"\fslice_config\x18\x03 \x01(\v2\x0f.slicemgr.SliceR\vsliceConfig\"L\n" +
	"\x16ConfigureSliceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x19E2NodeCapabilitiesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"@\n" +
	"\x1aE2NodeCapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities**\n" +
	"\tSliceType\x12\b\n" +
	"\x04EMBB\x10\x00\x12\t\n" +
	"\x05URLLC\x10\x01\x12\b\n" +
	"\x04MMTC\x10\x02*]\n" +
	"\n" +
	"SliceState\x12\v\n" +
	"\aCREATED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\v\n" +
	"\aSCALING\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\x0f\n" +
	"\vTERMINATING\x10\x05*>\n" +
	"\n" +
	"PolicyType\x12\a\n" +
	"\x03QOS\x10\x00\x12\r\n" +
	"\tRAN_SLICE\x10\x01\x12\x18\n" +
	"\x14RESOURCE_UTILIZATION\x10\x022\xca\a\n" +
	"\x16SliceManagementService\x12L\n" +
	"\vCreateSlice\x12\x1c.slicemgr.CreateSliceRequest\x1a\x1d.slicemgr.CreateSliceResponse\"\x00\x128\n" +
	"\bGetSlice\x12\x19.slicemgr.GetSliceRequest\x1a\x0f.slicemgr.Slice\"\x00\x12I\n" +
	"\n" +
	"ListSlices\x12\x1b.slicemgr.ListSlicesRequest\x1a\x1c.slicemgr.ListSlicesResponse\"\x00\x12>\n" +
	"\vUpdateSlice\x12\x1c.slicemgr.UpdateSliceRequest\x1a\x0f.slicemgr.Slice\"\x00\x12L\n" +
	"\vDeleteSlice\x12\x1c.slicemgr.DeleteSliceRequest\x1a\x1d.slicemgr.DeleteSliceResponse\"\x00\x12K\n" +
	"\x11CreateSlicePolicy\x12\x1d.slicemgr.CreatePolicyRequest\x1a\x15.slicemgr.SlicePolicy\"\x00\x12E\n" +
	"\x0eGetSlicePolicy\x12\x1a.slicemgr.GetPolicyRequest\x1a\x15.slicemgr.SlicePolicy\"\x00\x12K\n" +
	"\x11UpdateSlicePolicy\x12\x1d.slicemgr.UpdatePolicyRequest\x1a\x15.slicemgr.SlicePolicy\"\x00\x12T\n" +
	"\x11DeleteSlicePolicy\x12\x1d.slicemgr.DeletePolicyRequest\x1a\x1e.slicemgr.DeletePolicyResponse\"\x00\x12U\n" +
	"\x0eRegisterE2Node\x12\x1f.slicemgr.RegisterE2NodeRequest\x1a .slicemgr.RegisterE2NodeResponse\"\x00\x12[\n" +
	"\x14ConfigureSliceOnNode\x12\x1f.slicemgr.ConfigureSliceRequest\x1a .slicemgr.ConfigureSliceResponse\"\x00\x12d\n" +
	"\x15GetE2NodeCapabilities\x12#.slicemgr.E2NodeCapabilitiesRequest\x1a$.slicemgr.E2NodeCapabilitiesResponse\"\x00B4Z2github.com/your-org/near-rt-ric/api/proto/slicemgrb\x06proto3"

var (
	file_api_proto_slicemgr_slice_management_proto_rawDescOnce sync.Once
	file_api_proto_slicemgr_slice_management_proto_rawDescData []byte
)

func file_api_proto_slicemgr_slice_management_proto_rawDescGZIP() []byte {
	file_api_proto_slicemgr_slice_management_proto_rawDescOnce.Do(func() {
		file_api_proto_slicemgr_slice_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_slicemgr_slice_management_proto_rawDesc), len(file_api_proto_slicemgr_slice_management_proto_rawDesc)))
	})
	return file_api_proto_slicemgr_slice_management_proto_rawDescData
}

var file_api_proto_slicemgr_slice_management_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_slicemgr_slice_management_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_proto_slicemgr_slice_management_proto_goTypes = []any{
	(SliceType)(0),                     // 0: slicemgr.SliceType
	(SliceState)(0),                    // 1: slicemgr.SliceState
	(PolicyType)(0),                    // 2: slicemgr.PolicyType
	(*Slice)(nil),                      // 3: slicemgr.Slice
	(*ServiceProfile)(nil),             // 4: slicemgr.ServiceProfile
	(*DataRate)(nil),                   // 5: slicemgr.DataRate
	(*ResourceQuota)(nil),              // 6: slicemgr.ResourceQuota
	(*ComputeResources)(nil),           // 7: slicemgr.ComputeResources
	(*CPUResource)(nil),                // 8: slicemgr.CPUResource
	(*MemoryResource)(nil),             // 9: slicemgr.MemoryResource
	(*NetworkResources)(nil),           // 10: slicemgr.NetworkResources
	(*Bandwidth)(nil),                  // 11: slicemgr.Bandwidth
	(*StorageResources)(nil),           // 12: slicemgr.StorageResources
	(*SliceSLA)(nil),                   // 13: slicemgr.SliceSLA
	(*SLAObjectives)(nil),              // 14: slicemgr.SLAObjectives
	(*Throughput)(nil),                 // 15: slicemgr.Throughput
	(*Latency)(nil),                    // 16: slicemgr.Latency
	(*E2ELatency)(nil),                 // 17: slicemgr.E2ELatency
	(*RANLatency)(nil),                 // 18: slicemgr.RANLatency
	(*MonitoringConfig)(nil),           // 19: slicemgr.MonitoringConfig
	(*PlacementPolicy)(nil),            // 20: slicemgr.PlacementPolicy
	(*RegionPlacement)(nil),            // 21: slicemgr.RegionPlacement
	(*AffinityRule)(nil),               // 22: slicemgr.AffinityRule
	(*CreateSliceRequest)(nil),         // 23: slicemgr.CreateSliceRequest
	(*CreateSliceResponse)(nil),        // 24: slicemgr.CreateSliceResponse
	(*GetSliceRequest)(nil),            // 25: slicemgr.GetSliceRequest
	(*ListSlicesRequest)(nil),          // 26: slicemgr.ListSlicesRequest
	(*ListSlicesResponse)(nil),         // 27: slicemgr.ListSlicesResponse
	(*UpdateSliceRequest)(nil),         // 28: slicemgr.UpdateSliceRequest
	(*DeleteSliceRequest)(nil),         // 29: slicemgr.DeleteSliceRequest
	(*DeleteSliceResponse)(nil),        // 30: slicemgr.DeleteSliceResponse
	(*CreatePolicyRequest)(nil),        // 31: slicemgr.CreatePolicyRequest
	(*SlicePolicy)(nil),                // 32: slicemgr.SlicePolicy
	(*GetPolicyRequest)(nil),           // 33: slicemgr.GetPolicyRequest
	(*UpdatePolicyRequest)(nil),        // 34: slicemgr.UpdatePolicyRequest
	(*DeletePolicyRequest)(nil),        // 35: slicemgr.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),       // 36: slicemgr.DeletePolicyResponse
	(*RegisterE2NodeRequest)(nil),      // 37: slicemgr.RegisterE2NodeRequest
	(*RegisterE2NodeResponse)(nil),     // 38: slicemgr.RegisterE2NodeResponse
	(*ConfigureSliceRequest)(nil),      // 39: slicemgr.ConfigureSliceRequest
	(*ConfigureSliceResponse)(nil),     // 40: slicemgr.ConfigureSliceResponse
	(*E2NodeCapabilitiesRequest)(nil),  // 41: slicemgr.E2NodeCapabilitiesRequest
	(*E2NodeCapabilitiesResponse)(nil), // 42: slicemgr.E2NodeCapabilitiesResponse
	(*timestamppb.Timestamp)(nil),      // 43: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 44: google.protobuf.Struct
}
var file_api_proto_slicemgr_slice_management_proto_depIdxs = []int32{
	0,  // 0: slicemgr.Slice.type:type_name -> slicemgr.SliceType
	1,  // 1: slicemgr.Slice.state:type_name -> slicemgr.SliceState
	4,  // 2: slicemgr.Slice.service_profile:type_name -> slicemgr.ServiceProfile
	6,  // 3: slicemgr.Slice.resource_quota:type_name -> slicemgr.ResourceQuota
	13, // 4: slicemgr.Slice.sla:type_name -> slicemgr.SliceSLA
	20, // 5: slicemgr.Slice.placement:type_name -> slicemgr.PlacementPolicy
	43, // 6: slicemgr.Slice.created_at:type_name -> google.protobuf.Timestamp
	43, // 7: slicemgr.Slice.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 8: slicemgr.ServiceProfile.max_data_rate:type_name -> slicemgr.DataRate
	7,  // 9: slicemgr.ResourceQuota.compute:type_name -> slicemgr.ComputeResources
	10, // 10: slicemgr.ResourceQuota.network:type_name -> slicemgr.NetworkResources
	12, // 11: slicemgr.ResourceQuota.storage:type_name -> slicemgr.StorageResources
	8,  // 12: slicemgr.ComputeResources.cpu:type_name -> slicemgr.CPUResource
	9,  // 13: slicemgr.ComputeResources.memory:type_name -> slicemgr.MemoryResource
	11, // 14: slicemgr.NetworkResources.bandwidth:type_name -> slicemgr.Bandwidth
	14, // 15: slicemgr.SliceSLA.objectives:type_name -> slicemgr.SLAObjectives
	19, // 16: slicemgr.SliceSLA.monitoring:type_name -> slicemgr.MonitoringConfig
	15, // 17: slicemgr.SLAObjectives.throughput:type_name -> slicemgr.Throughput
	16, // 18: slicemgr.SLAObjectives.latency:type_name -> slicemgr.Latency
	5,  // 19: slicemgr.Throughput.downlink:type_name -> slicemgr.DataRate
	5,  // 20: slicemgr.Throughput.uplink:type_name -> slicemgr.DataRate
	17, // 21: slicemgr.Latency.e2e:type_name -> slicemgr.E2ELatency
	18, // 22: slicemgr.Latency.ran:type_name -> slicemgr.RANLatency
	21, // 23: slicemgr.PlacementPolicy.regions:type_name -> slicemgr.RegionPlacement
	22, // 24: slicemgr.PlacementPolicy.affinity:type_name -> slicemgr.AffinityRule
	22, // 25: slicemgr.PlacementPolicy.anti_affinity:type_name -> slicemgr.AffinityRule
	3,  // 26: slicemgr.CreateSliceRequest.slice:type_name -> slicemgr.Slice
	3,  // 27: slicemgr.CreateSliceResponse.slice:type_name -> slicemgr.Slice
	0,  // 28: slicemgr.ListSlicesRequest.type:type_name -> slicemgr.SliceType
	3,  // 29: slicemgr.ListSlicesResponse.slices:type_name -> slicemgr.Slice
	3,  // 30: slicemgr.UpdateSliceRequest.updated_slice:type_name -> slicemgr.Slice
	2,  // 31: slicemgr.CreatePolicyRequest.type:type_name -> slicemgr.PolicyType
	44, // 32: slicemgr.CreatePolicyRequest.policy_data:type_name -> google.protobuf.Struct
	2,  // 33: slicemgr.SlicePolicy.type:type_name -> slicemgr.PolicyType
	44, // 34: slicemgr.SlicePolicy.policy_instance:type_name -> google.protobuf.Struct
	43, // 35: slicemgr.SlicePolicy.created_at:type_name -> google.protobuf.Timestamp
	43, // 36: slicemgr.SlicePolicy.updated_at:type_name -> google.protobuf.Timestamp
	44, // 37: slicemgr.UpdatePolicyRequest.updated_policy:type_name -> google.protobuf.Struct
	3,  // 38: slicemgr.ConfigureSliceRequest.slice_config:type_name -> slicemgr.Slice
	23, // 39: slicemgr.SliceManagementService.CreateSlice:input_type -> slicemgr.CreateSliceRequest
	25, // 40: slicemgr.SliceManagementService.GetSlice:input_type -> slicemgr.GetSliceRequest
	26, // 41: slicemgr.SliceManagementService.ListSlices:input_type -> slicemgr.ListSlicesRequest
	28, // 42: slicemgr.SliceManagementService.UpdateSlice:input_type -> slicemgr.UpdateSliceRequest
	29, // 43: slicemgr.SliceManagementService.DeleteSlice:input_type -> slicemgr.DeleteSliceRequest
	31, // 44: slicemgr.SliceManagementService.CreateSlicePolicy:input_type -> slicemgr.CreatePolicyRequest
	33, // 45: slicemgr.SliceManagementService.GetSlicePolicy:input_type -> slicemgr.GetPolicyRequest
	34, // 46: slicemgr.SliceManagementService.UpdateSlicePolicy:input_type -> slicemgr.UpdatePolicyRequest
	35, // 47: slicemgr.SliceManagementService.DeleteSlicePolicy:input_type -> slicemgr.DeletePolicyRequest
	37, // 48: slicemgr.SliceManagementService.RegisterE2Node:input_type -> slicemgr.RegisterE2NodeRequest
	39, // 49: slicemgr.SliceManagementService.ConfigureSliceOnNode:input_type -> slicemgr.ConfigureSliceRequest
	41, // 50: slicemgr.SliceManagementService.GetE2NodeCapabilities:input_type -> slicemgr.E2NodeCapabilitiesRequest
	24, // 51: slicemgr.SliceManagementService.CreateSlice:output_type -> slicemgr.CreateSliceResponse
	3,  // 52: slicemgr.SliceManagementService.GetSlice:output_type -> slicemgr.Slice
	27, // 53: slicemgr.SliceManagementService.ListSlices:output_type -> slicemgr.ListSlicesResponse
	3,  // 54: slicemgr.SliceManagementService.UpdateSlice:output_type -> slicemgr.Slice
	30, // 55: slicemgr.SliceManagementService.DeleteSlice:output_type -> slicemgr.DeleteSliceResponse
	32, // 56: slicemgr.SliceManagementService.CreateSlicePolicy:output_type -> slicemgr.SlicePolicy
	32, // 57: slicemgr.SliceManagementService.GetSlicePolicy:output_type -> slicemgr.SlicePolicy
	32, // 58: slicemgr.SliceManagementService.UpdateSlicePolicy:output_type -> slicemgr.SlicePolicy
	36, // 59: slicemgr.SliceManagementService.DeleteSlicePolicy:output_type -> slicemgr.DeletePolicyResponse
	38, // 60: slicemgr.SliceManagementService.RegisterE2Node:output_type -> slicemgr.RegisterE2NodeResponse
	40, // 61: slicemgr.SliceManagementService.ConfigureSliceOnNode:output_type -> slicemgr.ConfigureSliceResponse
	42, // 62: slicemgr.SliceManagementService.GetE2NodeCapabilities:output_type -> slicemgr.E2NodeCapabilitiesResponse
	51, // [51:63] is the sub-list for method output_type
	39, // [39:51] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_api_proto_slicemgr_slice_management_proto_init() }
func file_api_proto_slicemgr_slice_management_proto_init() {
	if File_api_proto_slicemgr_slice_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_slicemgr_slice_management_proto_rawDesc), len(file_api_proto_slicemgr_slice_management_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_slicemgr_slice_management_proto_goTypes,
		DependencyIndexes: file_api_proto_slicemgr_slice_management_proto_depIdxs,
		EnumInfos:         file_api_proto_slicemgr_slice_management_proto_enumTypes,
		MessageInfos:      file_api_proto_slicemgr_slice_management_proto_msgTypes,
	}.Build()
	File_api_proto_slicemgr_slice_management_proto = out.File
	file_api_proto_slicemgr_slice_management_proto_goTypes = nil
	file_api_proto_slicemgr_slice_management_proto_depIdxs = nil
}
